package com.cxl;

import java.util.ArrayList;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ArrayAdapter;
import android.widget.ListView;

import com.cxl.shijieshangxiawuqiannian.R;

public class MainActivity extends Activity {
	ListView menuList;
	ArrayAdapter<KeyValue> menuAdapter;
	public static final ArrayList<KeyValue> MENU_List = new ArrayList<KeyValue>();
	static {
		MENU_List.add(new KeyValue("0", "0、前　　言"));
		MENU_List.add(new KeyValue("1", "1、失踪的国家"));
		MENU_List.add(new KeyValue("2", "2、说话的石碑"));
		MENU_List.add(new KeyValue("3", "3、千古之谜金字塔"));
		MENU_List.add(new KeyValue("4", "4、法老的诅咒"));
		MENU_List.add(new KeyValue("5", "5、大战卡叠石"));
		MENU_List.add(new KeyValue("6", "6、神奇古都底比斯"));
		MENU_List.add(new KeyValue("7", "7、太阳之子埃赫那吞"));
		MENU_List.add(new KeyValue("8", "8、太阳历和公历"));
		MENU_List.add(new KeyValue("9", "9、让人神往的美索不达米亚"));
		MENU_List.add(new KeyValue("10", "10、刻在泥版上的文字"));
		MENU_List.add(new KeyValue("11", "11、汉谟拉比和刻在石柱上的法典"));
		MENU_List.add(new KeyValue("12", "12、流浪的犹太民族"));
		MENU_List.add(new KeyValue("13", "13、寻找金约柜和所罗门珍宝"));
		MENU_List.add(new KeyValue("14", "14、紫红色的人"));
		MENU_List.add(new KeyValue("15", "15、亚述帝国与血腥的狮穴"));
		MENU_List.add(new KeyValue("16", "16、尼布甲尼撒二世"));
		MENU_List.add(new KeyValue("17", "17、冒犯上帝的城市巴比伦"));
		MENU_List.add(new KeyValue("18", "18、宇宙之王居鲁士"));
		MENU_List.add(new KeyValue("19", "19、暴君冈比西斯"));
		MENU_List.add(new KeyValue("20", "20、大流士改革"));
		MENU_List.add(new KeyValue("21", "21、埋在死人之丘下的城市"));
		MENU_List.add(new KeyValue("22", "22、古代印度的种姓制度"));
		MENU_List.add(new KeyValue("23", "23、佛祖和佛教"));
		MENU_List.add(new KeyValue("24", "24、伟大的阿育王"));
		MENU_List.add(new KeyValue("25", "25、《摩诃婆罗多》"));
		MENU_List.add(new KeyValue("26", "26、地下迷宫"));
		MENU_List.add(new KeyValue("27", "27、荷　　马"));
		MENU_List.add(new KeyValue("28", "28、木　马　计"));
		MENU_List.add(new KeyValue("29", "29、奥林匹亚赛会"));
		MENU_List.add(new KeyValue("30", "30、斯　巴　达"));
		MENU_List.add(new KeyValue("31", "31、改革家梭伦"));
		MENU_List.add(new KeyValue("32", "32、马　拉　松"));
		MENU_List.add(new KeyValue("33", "33、血战温泉关"));
		MENU_List.add(new KeyValue("34", "34、萨拉米湾海战"));
		MENU_List.add(new KeyValue("35", "35、伯里克利与雅典"));
		MENU_List.add(new KeyValue("36", "36、雅典的民主"));
		MENU_List.add(new KeyValue("37", "37、希罗多德"));
		MENU_List.add(new KeyValue("38", "38、苏格拉底"));
		MENU_List.add(new KeyValue("39", "39、希波克拉底"));
		MENU_List.add(new KeyValue("40", "40、柏　拉　图"));
		MENU_List.add(new KeyValue("41", "41、西西里之战"));
		MENU_List.add(new KeyValue("42", "42、亚里士多德"));
		MENU_List.add(new KeyValue("43", "43、雄辩家德摩斯梯尼"));
		MENU_List.add(new KeyValue("44", "44、伊索的寓言"));
		MENU_List.add(new KeyValue("45", "45、亚历山大"));
		MENU_List.add(new KeyValue("46", "46、格拉尼库斯河战役"));
		MENU_List.add(new KeyValue("47", "47、罗马和母狼"));
		MENU_List.add(new KeyValue("48", "48、法西斯笞棒"));
		MENU_List.add(new KeyValue("49", "49、穆基乌斯"));
		MENU_List.add(new KeyValue("50", "50、罗马与白鹅"));
		MENU_List.add(new KeyValue("51", "51、向贵族宣战"));
		MENU_List.add(new KeyValue("52", "52、坦克―战象"));
		MENU_List.add(new KeyValue("53", "53、乌鸦式战舰"));
		MENU_List.add(new KeyValue("54", "54、阿基米德"));
		MENU_List.add(new KeyValue("55", "55、汉尼拔"));
		MENU_List.add(new KeyValue("56", "56、康奈城激战"));
		MENU_List.add(new KeyValue("57", "57、格拉古兄弟"));
		MENU_List.add(new KeyValue("58", "58、斯巴达克起义"));
		MENU_List.add(new KeyValue("59", "59、马略与苏拉"));
		MENU_List.add(new KeyValue("60", "60、恺　　撒"));
		MENU_List.add(new KeyValue("61", "61、庞　　培"));
		MENU_List.add(new KeyValue("62", "62、克拉苏"));
		MENU_List.add(new KeyValue("63", "63、奥古斯都"));
		MENU_List.add(new KeyValue("64", "64、尼　　禄"));
		MENU_List.add(new KeyValue("65", "65、耶　　稣"));
		MENU_List.add(new KeyValue("66", "66、奥古斯丁"));
		MENU_List.add(new KeyValue("67", "67、古城庞贝"));
		MENU_List.add(new KeyValue("68", "68、罗马帝国的灭亡"));
		MENU_List.add(new KeyValue("69", "69、查理大帝"));
		MENU_List.add(new KeyValue("70", "70、查士丁尼"));
		MENU_List.add(new KeyValue("71", "71、中世纪骑士"));
		MENU_List.add(new KeyValue("72", "72、日本的大化改新"));
		MENU_List.add(new KeyValue("73", "73、遣　唐　使"));
		MENU_List.add(new KeyValue("74", "74、西天在哪里"));
		MENU_List.add(new KeyValue("75", "75、十字军东侵"));
		MENU_List.add(new KeyValue("76", "76、扎克雷起义"));
		MENU_List.add(new KeyValue("77", "77、基辅罗斯的盛衰"));
		MENU_List.add(new KeyValue("78", "78、君士坦丁堡的陷落"));
		MENU_List.add(new KeyValue("79", "79、马丁·路德"));
		MENU_List.add(new KeyValue("80", "80、勇敢的闵采尔"));
		MENU_List.add(new KeyValue("81", "81、日内瓦的教皇加尔文"));
		MENU_List.add(new KeyValue("82", "82、穆罕默德和伊斯兰教"));
		MENU_List.add(new KeyValue("83", "83、《一千零一夜》"));
		MENU_List.add(new KeyValue("84", "84、马可·波罗"));
		MENU_List.add(new KeyValue("85", "85、阿　克　巴"));
		MENU_List.add(new KeyValue("86", "86、横跨欧亚非的奥斯曼帝国"));
		MENU_List.add(new KeyValue("87", "87、新航路的开辟"));
		MENU_List.add(new KeyValue("88", "88、瓦斯科·达·伽马"));
		MENU_List.add(new KeyValue("89", "89、麦　哲　伦"));
		MENU_List.add(new KeyValue("90", "90、羊吃人的圈地运动"));
		MENU_List.add(new KeyValue("91", "91、托马斯·阿奎那"));
		MENU_List.add(new KeyValue("92", "92、文艺复兴"));
		MENU_List.add(new KeyValue("93", "93、彼脱拉克"));
		MENU_List.add(new KeyValue("94", "94、但丁与《神曲》"));
		MENU_List.add(new KeyValue("95", "95、薄伽丘与《十日谈》"));
		MENU_List.add(new KeyValue("96", "96、拉伯雷与《巨人传》"));
		MENU_List.add(new KeyValue("97", "97、莎士比亚"));
		MENU_List.add(new KeyValue("98", "98、大侠堂吉诃德"));
		MENU_List.add(new KeyValue("99", "99、康帕内拉的《太阳城》"));
		MENU_List.add(new KeyValue("100", "100、迦梨陀娑和《沙恭达罗》"));
		MENU_List.add(new KeyValue("101", "101、米开朗基罗"));
		MENU_List.add(new KeyValue("102", "102、达·芬奇"));
		MENU_List.add(new KeyValue("103", "103、伽　利　略"));
		MENU_List.add(new KeyValue("104", "104、哥　白　尼"));
		MENU_List.add(new KeyValue("105", "105、培　　根"));
		MENU_List.add(new KeyValue("106", "106、捷克胡司战争"));
		MENU_List.add(new KeyValue("107", "107、掷出窗外事件"));
		MENU_List.add(new KeyValue("108", "108、李舜臣和壬辰卫国战争"));
		MENU_List.add(new KeyValue("109", "109、“乞丐”的国家"));
		MENU_List.add(new KeyValue("110", "110、断头的国王"));
		MENU_List.add(new KeyValue("111", "111、未戴王冠的英国国王――克伦威尔"));
		MENU_List.add(new KeyValue("112", "112、“进口”的国王和“光荣革命”"));
		MENU_List.add(new KeyValue("113", "113、俄罗斯帝国的创立者――彼得大帝"));
		MENU_List.add(new KeyValue("114", "114、彼得大帝两次围攻纳尔瓦"));
		MENU_List.add(new KeyValue("115", "115、蒸汽机的真正发明者"));
		MENU_List.add(new KeyValue("116", "116、伟大的科学家牛顿"));
		MENU_List.add(new KeyValue("117", "117、“海上马车夫”"));
		MENU_List.add(new KeyValue("118", "118、美国独立战争的第一枪"));
		MENU_List.add(new KeyValue("119", "119、美利坚合众国的缔造者――华盛顿"));
		MENU_List.add(new KeyValue("120", "120、揭开雷电之谜的人――富兰克林"));
		MENU_List.add(new KeyValue("121", "121、马背上的英雄――美国牛仔"));
		MENU_List.add(new KeyValue("122", "122、谢司起义"));
		MENU_List.add(new KeyValue("123", "123、启蒙运动的领袖――伏尔泰"));
		MENU_List.add(new KeyValue("124", "124、攻占巴士底狱"));
		MENU_List.add(new KeyValue("125", "125、罗伯斯比尔"));
		MENU_List.add(new KeyValue("126", "126、刽子手·国王·断头台"));
		MENU_List.add(new KeyValue("127", "127、青年拿破仑"));
		MENU_List.add(new KeyValue("128", "128、“雾月政变”"));
		MENU_List.add(new KeyValue("129", "129、教皇算什么！"));
		MENU_List.add(new KeyValue("130", "130、会战马伦哥"));
		MENU_List.add(new KeyValue("131", "131、乌耳姆战役"));
		MENU_List.add(new KeyValue("132", "132、奥斯特里茨之战"));
		MENU_List.add(new KeyValue("133", "133、拿破仑兵败俄国"));
		MENU_List.add(new KeyValue("134", "134、滑铁卢战役"));
		MENU_List.add(new KeyValue("135", "135、达尔文和他的“进化论”"));
		MENU_List.add(new KeyValue("136", "136、世界音乐大师贝多芬"));
		MENU_List.add(new KeyValue("137", "137、野心勃勃的女沙皇――叶卡杰琳娜二世"));
		MENU_List.add(new KeyValue("138", "138、普加乔夫起义"));
		MENU_List.add(new KeyValue("139", "139、俄国革命的先驱――１２月党人"));
		MENU_List.add(new KeyValue("140", "140、雨果"));
		MENU_List.add(new KeyValue("141", "141、“俄国文学的始祖”――普希金"));
		MENU_List.add(new KeyValue("142", "142、文学史上的拿破仑"));
		MENU_List.add(new KeyValue("143", "143、果戈理"));
		MENU_List.add(new KeyValue("144", "144、“万古不朽”圣马丁"));
		MENU_List.add(new KeyValue("145", "145、“解放者”玻利瓦尔"));
		MENU_List.add(new KeyValue("146", "146、人类的耻辱――奴隶贸易"));
		MENU_List.add(new KeyValue("147", "147、自由海地的诞生"));
		MENU_List.add(new KeyValue("148", "148、电灯的发明"));
		MENU_List.add(new KeyValue("149", "149、欧文和他的“新和谐公社”"));
		MENU_List.add(new KeyValue("150", "150、青年马克思"));
		MENU_List.add(new KeyValue("151", "151、恩格斯的青年时代"));
		MENU_List.add(new KeyValue("152", "152、惊天动地的红色宣言"));
		MENU_List.add(new KeyValue("153", "153、《资本论》的诞生"));
		MENU_List.add(new KeyValue("154", "154、第一个国际工人的组织――第一国际"));
		MENU_List.add(new KeyValue("155", "155、铁血宰相俾斯麦"));
		MENU_List.add(new KeyValue("156", "156、色当战役"));
		MENU_List.add(new KeyValue("157", "157、三月十八日武装起义"));
		MENU_List.add(new KeyValue("158", "158、悲壮的“五月流血周”"));
		MENU_List.add(new KeyValue("159", "159、民族英雄蒂博尼哥罗"));
		MENU_List.add(new KeyValue("160", "160、巴布教徒的“正义王国”"));
		MENU_List.add(new KeyValue("161", "161、东印度公司"));
		MENU_List.add(new KeyValue("162", "162、章西女王葩依"));
		MENU_List.add(new KeyValue("163", "163、德里反英大起义"));
		MENU_List.add(new KeyValue("164", "164、约翰·布朗起义"));
		MENU_List.add(new KeyValue("165", "165、林肯"));
		MENU_List.add(new KeyValue("166", "166、唐纳尔逊堡大战"));
		MENU_List.add(new KeyValue("167", "167、维克斯堡战役"));
		MENU_List.add(new KeyValue("168", "168、血战葛底斯堡"));
		MENU_List.add(new KeyValue("169", "169、弗吉尼亚大会战"));
		MENU_List.add(new KeyValue("170", "170、陀思妥耶夫斯基"));
		MENU_List.add(new KeyValue("171", "171、病菌和病毒的发现者――巴斯德"));
		MENU_List.add(new KeyValue("172", "172、国际航道――苏伊士运河"));
		MENU_List.add(new KeyValue("173", "173、马赫迪大破英军"));
		MENU_List.add(new KeyValue("174", "174、“倒幕”运动与明治维新"));
		MENU_List.add(new KeyValue("175", "175、飞机的发明者莱特兄弟"));
		MENU_List.add(new KeyValue("176", "176、列宁的青年时代"));
		MENU_List.add(new KeyValue("177", "177、“五一”国际劳动节"));
		MENU_List.add(new KeyValue("178", "178、生理学无冕之王――巴甫洛夫"));
		MENU_List.add(new KeyValue("179", "179、德雷福斯冤案"));
		MENU_List.add(new KeyValue("180", "180、“Ｘ射线”是如何发现的"));
		MENU_List.add(new KeyValue("181", "181、“缅因”号事件"));
		MENU_List.add(new KeyValue("182", "182、星期日惨案"));
		MENU_List.add(new KeyValue("183", "183、“诺贝尔奖金”的由来"));
		MENU_List.add(new KeyValue("184", "184、居里夫人"));
		MENU_List.add(new KeyValue("185", "185、日俄旅顺战役"));
		MENU_List.add(new KeyValue("186", "186、爱因斯坦和他的“相对论”"));
		MENU_List.add(new KeyValue("187", "187、震惊世界的“萨拉热窝枪声”"));
		MENU_List.add(new KeyValue("188", "188、“史里芬计划”的破灭"));
		MENU_List.add(new KeyValue("189", "189、德俄“坦仑堡战役”"));
		MENU_List.add(new KeyValue("190", "190、人类历史上的第一次毒气战"));
		MENU_List.add(new KeyValue("191", "191、“神秘之船”在行动"));
		MENU_List.add(new KeyValue("192", "192、英德海上大决战"));
		MENU_List.add(new KeyValue("193", "193、凡尔登战役"));
		MENU_List.add(new KeyValue("194", "194、坦克的前身――“机枪破坏器”"));
		MENU_List.add(new KeyValue("195", "195、“信使”彻尔·阿米"));
		MENU_List.add(new KeyValue("196", "196、兰斯保卫战"));
		MENU_List.add(new KeyValue("197", "197、攻占冬宫"));
		MENU_List.add(new KeyValue("198", "198、德意志风云"));
		MENU_List.add(new KeyValue("199", "199、巴黎和会"));
		MENU_List.add(new KeyValue("200", "200、米骚动"));
		MENU_List.add(new KeyValue("201", "201、新经济政策"));
		MENU_List.add(new KeyValue("202", "202、青年人的任务"));
		MENU_List.add(new KeyValue("203", "203、“星期六义务劳动”"));
		MENU_List.add(new KeyValue("204", "204、列宁逝世"));
		MENU_List.add(new KeyValue("205", "205、经济危机"));
		MENU_List.add(new KeyValue("206", "206、从“流浪汉”到“第三帝国”总理"));
		MENU_List.add(new KeyValue("207", "207、“国会纵火案”"));
		MENU_List.add(new KeyValue("208", "208、“二·二六”暴乱"));
		MENU_List.add(new KeyValue("209", "209、日军间谍与“九·一八”事变"));
		MENU_List.add(new KeyValue("210", "210、埃塞俄比亚的抗战"));
		MENU_List.add(new KeyValue("211", "211、保卫马德里"));
		MENU_List.add(new KeyValue("212", "212、“和平鸽”的父亲"));
		MENU_List.add(new KeyValue("213", "213、慕尼黑阴谋"));
		MENU_List.add(new KeyValue("214", "214、“消灭褐色瘟疫”"));
		MENU_List.add(new KeyValue("215", "215、电视的发明"));
		MENU_List.add(new KeyValue("216", "216、“硬汉子”海明威"));
		MENU_List.add(new KeyValue("217", "217、“圣雄”甘地"));
		MENU_List.add(new KeyValue("218", "218、土耳其之父"));
		MENU_List.add(new KeyValue("219", "219、巴基斯坦国的创建者"));
		MENU_List.add(new KeyValue("220", "220、朝鲜“三·一”运动"));
		MENU_List.add(new KeyValue("221", "221、自由人的将军桑地诺"));
		MENU_List.add(new KeyValue("222", "222、揭开原子秘密的人"));
		MENU_List.add(new KeyValue("223", "223、火箭发明家"));
		MENU_List.add(new KeyValue("224", "224、青霉素的发现"));
		MENU_List.add(new KeyValue("225", "225、第一颗原子弹"));
		MENU_List.add(new KeyValue("226", "226、“白色方案”和“海狮计划”"));
		MENU_List.add(new KeyValue("227", "227、敦刻尔克大撤退"));
		MENU_List.add(new KeyValue("228", "228、“巴巴罗沙”计划"));
		MENU_List.add(new KeyValue("229", "229、斯大林格勒保卫战"));
		MENU_List.add(new KeyValue("230", "230、保卫列宁格勒"));
		MENU_List.add(new KeyValue("231", "231、“红色间谍”"));
		MENU_List.add(new KeyValue("232", "232、安妮·弗兰克日记"));
		MENU_List.add(new KeyValue("233", "233、“杀人工厂”"));
		MENU_List.add(new KeyValue("234", "234、绞刑架下的报告"));
		MENU_List.add(new KeyValue("235", "235、地下救援组织"));
		MENU_List.add(new KeyValue("236", "236、通往自由的隧道"));
		MENU_List.add(new KeyValue("237", "237、伏击杀人魔王"));
		MENU_List.add(new KeyValue("238", "238、红衣女谍"));
		MENU_List.add(new KeyValue("239", "239、勇敢的“燕子”"));
		MENU_List.add(new KeyValue("240", "240、运送十八亿英镑"));
		MENU_List.add(new KeyValue("241", "241、围歼“俾斯麦”"));
		MENU_List.add(new KeyValue("242", "242、勇敢的女船长"));
		MENU_List.add(new KeyValue("243", "243、沙漠猎“狐”"));
		MENU_List.add(new KeyValue("244", "244、“自由法国”运动"));
		MENU_List.add(new KeyValue("245", "245、珍珠港怪客"));
		MENU_List.add(new KeyValue("246", "246、偷袭珍珠港"));
		MENU_List.add(new KeyValue("247", "247、中途岛海战"));
		MENU_List.add(new KeyValue("248", "248、乔伊的故事"));
		MENU_List.add(new KeyValue("249", "249、“第三战场”的无名勇士"));
		MENU_List.add(new KeyValue("250", "250、挪威英雄"));
		MENU_List.add(new KeyValue("251", "251、“魔术师”似的密码破译专家"));
		MENU_List.add(new KeyValue("252", "252、希特勒的“敌后武工队”"));
		MENU_List.add(new KeyValue("253", "253、背叛“祖国”的纳粹党创始人"));
		MENU_List.add(new KeyValue("254", "254、“海狼”与海鸥"));
		MENU_List.add(new KeyValue("255", "255、直布罗陀海底的“人鱼雷”"));
		MENU_List.add(new KeyValue("256", "256、假电报瞒天过海日舰队偷袭成功"));
		MENU_List.add(new KeyValue("257", "257、龙田丸示假隐真假水兵招摇过市"));
		MENU_List.add(new KeyValue("258", "258、密写信中的间谍线索"));
		MENU_List.add(new KeyValue("259", "259、来自背后的奇袭"));
		MENU_List.add(new KeyValue("260", "260、走向死亡的行军"));
		MENU_List.add(new KeyValue("261", "261、杜立德首炸东京"));
		MENU_List.add(new KeyValue("262", "262、瓜岛之战中的“老鼠特快”"));
		MENU_List.add(new KeyValue("263", "263、传单上的投降证"));
		MENU_List.add(new KeyValue("264", "264、不到４分钟的“复仇行动”"));
		MENU_List.add(new KeyValue("265", "265、引诱纳粹上钩的“肉馅”"));
		MENU_List.add(new KeyValue("266", "266、诺曼底登陆"));
		MENU_List.add(new KeyValue("267", "267、袭击美国的“飞象”"));
		MENU_List.add(new KeyValue("268", "268、电子干扰制造的大骗局"));
		MENU_List.add(new KeyValue("269", "269、普罗霍夫卡草原上的坦克大战"));
		MENU_List.add(new KeyValue("270", "270、毁灭汉堡的“反射体”"));
		MENU_List.add(new KeyValue("271", "271、夜袭佩内明德"));
		MENU_List.add(new KeyValue("272", "272、穷凶极恶的纳粹别动队"));
		MENU_List.add(new KeyValue("273", "273、海里捞起来的绝密公文包"));
		MENU_List.add(new KeyValue("274", "274、日军惨败英帕尔"));
		MENU_List.add(new KeyValue("275", "275、尼米兹的“奇袭行动”"));
		MENU_List.add(new KeyValue("276", "276、马里亚纳的大规模火鸡射击战"));
		MENU_List.add(new KeyValue("277", "277、垂死挣扎的“神风特攻”"));
		MENU_List.add(new KeyValue("278", "278、静悄悄的瞬间奇袭"));
		MENU_List.add(new KeyValue("279", "279、穿美军制服的德国兵"));
		MENU_List.add(new KeyValue("280", "280、超级战列舰的覆灭"));
		MENU_List.add(new KeyValue("281", "281、阿登山林的激战"));
		MENU_List.add(new KeyValue("282", "282、“雷击”德累斯顿"));
		MENU_List.add(new KeyValue("283", "283、血战硫黄岛"));
		MENU_List.add(new KeyValue("284", "284、飞夺雷马根桥"));
		MENU_List.add(new KeyValue("285", "285、夜空中燃烧的江户花"));
		MENU_List.add(new KeyValue("286", "286、冲绳之战"));
		MENU_List.add(new KeyValue("287", "287、击沉大和号"));
		MENU_List.add(new KeyValue("288", "288、杰出的参谋长马歇尔"));
		MENU_List.add(new KeyValue("289", "289、爱冒险的麦克阿瑟"));
		MENU_List.add(new KeyValue("290", "290、血胆将军巴顿"));
		MENU_List.add(new KeyValue("291", "291、临危受命不负众望的尼米兹"));
		MENU_List.add(new KeyValue("292", "292、军人政治家外交家艾森豪威尔"));
		MENU_List.add(new KeyValue("293", "293、一位工人和革命士兵――伏罗希洛夫"));
		MENU_List.add(new KeyValue("294", "294、传奇英雄布琼尼"));
		MENU_List.add(new KeyValue("295", "295、稳健持重的华西列夫斯基"));
		MENU_List.add(new KeyValue("296", "296、最高副统帅朱可夫"));
		MENU_List.add(new KeyValue("297", "297、“沙漠之鼠”蒙哥马利"));
		MENU_List.add(new KeyValue("298", "298、德国陆军的元老伦德施泰特"));
		MENU_List.add(new KeyValue("299", "299、富有创见的曼施泰因"));
		MENU_List.add(new KeyValue("300", "300、“闪击英雄”古德里安"));
		MENU_List.add(new KeyValue("301", "301、“沙漠之狐”隆美尔"));
		MENU_List.add(new KeyValue("302", "302、纳粹之“鹰”凯塞林"));
		MENU_List.add(new KeyValue("303", "303、战争恶魔东条英机"));
		MENU_List.add(new KeyValue("304", "304、山本五十六"));
		MENU_List.add(new KeyValue("305", "305、德黑兰会议"));
		MENU_List.add(new KeyValue("306", "306、刺杀希特勒"));
		MENU_List.add(new KeyValue("307", "307、拙劣的“跳马”"));
		MENU_List.add(new KeyValue("308", "308、墨索里尼的末日"));
		MENU_List.add(new KeyValue("309", "309、希特勒的末日"));
		MENU_List.add(new KeyValue("310", "310、广岛“蘑菇云”"));
		MENU_List.add(new KeyValue("311", "311、日本投降"));
		MENU_List.add(new KeyValue("312", "312、正义的审判"));
		MENU_List.add(new KeyValue("313", "313、联合国成立"));


	}



	/** Called when the activity is first created. */
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.main);
		menuList = (ListView) findViewById(R.id.menuList);
		menuAdapter = new ArrayAdapter<KeyValue>(this,
				R.layout.simple_list_layout, R.id.txtListItem, MENU_List);
		menuList.setAdapter(menuAdapter);
		menuList.setOnItemClickListener(new OnItemClickListener() {
			public void onItemClick(AdapterView<?> arg0, View arg1, int pos,
					long id) {
				KeyValue menu = (KeyValue) arg0.getItemAtPosition(pos);
				Intent intent = new Intent();
				intent.setClass(MainActivity.this, DetailActivity.class);
				Bundle bundle = new Bundle();
				bundle.putString("menu", menu.getKey());
				bundle.putBoolean("startByMenu", true);
				intent.putExtras(bundle);
				startActivity(intent);
				finish();
			}
		});
	}
}