var format = {
	"data" : {
		"address" : "",
		"anno" : "",
		"availablePath" : "保存,拟办",
		"collapsedSugFields" : "",
		"content" : "yjkjhgf",
		"curAllTaskNodeName" : "会议登记",
		"curLockUser" : "",
		"curNodeName" : "会议登记",
		"curProcessors" : "admin",
		"curSelectActor" : "",
		"curSelectActorFullName" : "",
		"curSuggestion" : "",
		"curSuggestionNodeSort" : "",
		"curTrans" : "",
		"curUser" : "admin",
		"delAddedAttachIds" : "",
		"delAttachIds" : "",
		"department" : "",
		"editFields" : "meetingNumber,meetingTime,attachPanel,afterMettingAttachPanel,fromCompany,address,curSuggestion,receiveTime,recordMan,leader,receiveNumber,recordDate,department,content,anno,beforeMettingAttachPanel",
		"emergencyDegree" : "0",
		"flowName" : "MeetingNoticeFlow",
		"fromCompany" : "",
		"hideFields" : "",
		"id" : 4318,
		"leader" : "",
		"meetingNumber" : "会议20110301",
		"meetingTime" : "2011-07-27 16:22:34",
		"multiEdit" : "false",
		"newAfterMettingAttachs" : [{
					"attachFileBinary" : null,
					"attachFileSize" : 4040,
					"contentType" : "text/plain",
					"fileName" : "请用我机器的连接，对net的文件交换发送做分块发送测试.txt",
					"id" : 25,
					"processId" : 4318
				}, {
					"attachFileBinary" : null,
					"attachFileSize" : 340,
					"contentType" : "text/plain",
					"fileName" : "流程节点note.txt",
					"id" : 24,
					"processId" : 4318
				}, {
					"attachFileBinary" : null,
					"attachFileSize" : 4696,
					"contentType" : "image/pjpeg",
					"fileName" : "兔斯基.jpg",
					"id" : 26,
					"processId" : 4318
				}],
		"newBeforeMettingAttachs" : [{
					"attachFileBinary" : null,
					"attachFileSize" : 29696,
					"contentType" : "application/vnd.ms-excel",
					"fileName" : "【归档项目更新】版本说明列表.xls",
					"id" : 23,
					"processId" : 4318
				}, {
					"attachFileBinary" : null,
					"attachFileSize" : 64512,
					"contentType" : "application/msword",
					"fileName" : "个人设置_增加设置流程操作之后关闭或刷新页面.doc",
					"id" : 24,
					"processId" : 4318
				}],
		"operationType" : 0,
		"participator" : "admin,longjianbin,chenwenmian,liangjingjing,zhongzhenhua,administrator,chenbaojun,qiguoqiang,yangyingying,yuxiquan,liufucai,tangzhifen,yuziran,zhangxiaomu,zhanghuaiyou,linguanyu,chenhongyong,honglihong,wuqingquan,panlinzhu,qinwenbo,linsanlin,wenguohui,wuguangming,chenzhirong,admin,xiaoxue,gaosanmao,zhaoruiyun",
		"personalSubmitMode" : "0",
		"processId" : 4318,
		"processTitle" : "yjkjhgf",
		"receiveNumber" : "",
		"receiveTime" : "2011-07-27 16:22:34",
		"recordDate" : "2011-07-27 16:22:34",
		"recordMan" : "admin",
		"relationProcess" : "",
		"suggestionsInfo" : "{\"list\":[]}",
		"taskId" : 49961,
		"workFlowAddedAttachs" : [],
		"workFlowDBAttachs" : [],
		"workflowProcessInfo" : {
			"currentStepName" : "会议登记",
			"docExported" : 0,
			"haveAttach" : false,
			"haveMainText" : false,
			"id" : 4318,
			"isLocked" : 0,
			"lockBeginTime" : "2011-07-27 16:25:22",
			"lockOwner" : "",
			"processDuration" : 0,
			"processId" : 4318,
			"processName" : "MeetingNoticeFlow",
			"processTitle" : "yjkjhgf",
			"status" : 0,
			"sysActorName" : "admin;admin",
			"sysCreateTime" : "2011-07-27 16:25:22",
			"sysCreator" : "admin",
			"sysCreatorName" : "admin",
			"sysCurNode" : "会议登记",
			"sysCurrentProcessors" : "admin",
			"sysDynamicActor" : "会议登记:admin",
			"sysDynamicActorFullName" : "会议登记:admin",
			"sysDynamicTaskId" : 0,
			"sysEmergency" : 0,
			"sysSubmitTime" : "2011-07-27 16:25:22"
		}
	},
	"success" : true
}