package com.cxl;

import java.util.ArrayList;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ArrayAdapter;
import android.widget.ListView;

import com.cxl.gshmr.R;

public class MainActivity extends Activity {
	ListView menuList;
	ArrayAdapter<KeyValue> menuAdapter;
	public static final ArrayList<KeyValue> MENU_List = new ArrayList<KeyValue>();
	static {
		MENU_List.add(new KeyValue("0", "0、用幽默塑造智慧"));
		MENU_List.add(new KeyValue("1", "1、成功"));
		MENU_List.add(new KeyValue("2", "2、远山"));
		MENU_List.add(new KeyValue("3", "3、饭钱"));
		MENU_List.add(new KeyValue("4", "4、心态测试"));
		MENU_List.add(new KeyValue("5", "5、丁肇中的“不知道”"));
		MENU_List.add(new KeyValue("6", "6、谁都不能改变我的承诺"));
		MENU_List.add(new KeyValue("7", "7、怜悯可以走多远"));
		MENU_List.add(new KeyValue("8", "8、富有更多表现在内心里"));
		MENU_List.add(new KeyValue("9", "9、上帝本没有光环"));
		MENU_List.add(new KeyValue("10", "10、高贵的自由"));
		MENU_List.add(new KeyValue("11", "11、玫瑰花信誓"));
		MENU_List.add(new KeyValue("12", "12、无人涉足的地方"));
		MENU_List.add(new KeyValue("13", "13、把“名声”送给别人"));
		MENU_List.add(new KeyValue("14", "14、举世无双的报酬"));
		MENU_List.add(new KeyValue("15", "15、真实的高度"));
		MENU_List.add(new KeyValue("16", "16、穆律罗的骄傲"));
		MENU_List.add(new KeyValue("17", "17、冒牌货"));
		MENU_List.add(new KeyValue("18", "18、梦想是一件粗布衣"));
		MENU_List.add(new KeyValue("19", "19、牌是上帝发的"));
		MENU_List.add(new KeyValue("20", "20、母爱与肝脏透析"));
		MENU_List.add(new KeyValue("21", "21、落水者和负重者"));
		MENU_List.add(new KeyValue("22", "22、永不退缩的林肯总统"));
		MENU_List.add(new KeyValue("23", "23、认识到自己的好"));
		MENU_List.add(new KeyValue("24", "24、沉没成本"));
		MENU_List.add(new KeyValue("25", "25、疼痛是个好消息"));
		MENU_List.add(new KeyValue("26", "26、成人之美"));
		MENU_List.add(new KeyValue("27", "27、半杯理论"));
		MENU_List.add(new KeyValue("28", "28、该低头时就低头"));
		MENU_List.add(new KeyValue("29", "29、天道酬勤"));
		MENU_List.add(new KeyValue("30", "30、黄帝问路"));
		MENU_List.add(new KeyValue("31", "31、知音难觅乎"));
		MENU_List.add(new KeyValue("32", "32、卡特给里根的锦囊妙计"));
		MENU_List.add(new KeyValue("33", "33、暴龙"));
		MENU_List.add(new KeyValue("34", "34、曼德拉的顿悟"));
		MENU_List.add(new KeyValue("35", "35、自己拿主意"));
		MENU_List.add(new KeyValue("36", "36、口才决定命运"));
		MENU_List.add(new KeyValue("37", "37、不要为卑微的东西祈祷"));
		MENU_List.add(new KeyValue("38", "38、父亲接我回家"));
		MENU_List.add(new KeyValue("39", "39、降低快乐的标准"));
		MENU_List.add(new KeyValue("40", "40、改变人生的一句话"));
		MENU_List.add(new KeyValue("41", "41、一言救世界"));
		MENU_List.add(new KeyValue("42", "42、错误的恐慌"));
		MENU_List.add(new KeyValue("43", "43、别开生面的告别"));
		MENU_List.add(new KeyValue("44", "44、敞开新的大门"));
		MENU_List.add(new KeyValue("45", "45、绝处求生"));
		MENU_List.add(new KeyValue("46", "46、用心听人说话"));
		MENU_List.add(new KeyValue("47", "47、欣赏是一种善良"));
		MENU_List.add(new KeyValue("48", "48、比尔-盖茨的精明和浅薄"));
		MENU_List.add(new KeyValue("49", "49、控制情绪"));
		MENU_List.add(new KeyValue("50", "50、力量"));
		MENU_List.add(new KeyValue("51", "51、财富修养"));
		MENU_List.add(new KeyValue("52", "52、一双鞋"));
		MENU_List.add(new KeyValue("53", "53、当机立断"));
		MENU_List.add(new KeyValue("54", "54、为什么么我要让他决定我的行为？"));
		MENU_List.add(new KeyValue("55", "55、用皮鞋演奏的帕格尼尼"));
		MENU_List.add(new KeyValue("56", "56、谦逊的贝罗尼"));
		MENU_List.add(new KeyValue("57", "57、一个人的简历(林肯)"));
		MENU_List.add(new KeyValue("58", "58、逼出来的天才"));
		MENU_List.add(new KeyValue("59", "59、洛克菲勒孙子怎么花零用钱"));
		MENU_List.add(new KeyValue("60", "60、一件“小事”与两个伟人"));
		MENU_List.add(new KeyValue("61", "61、君子之争"));
		MENU_List.add(new KeyValue("62", "62、拿破仑与皮毛商人"));
		MENU_List.add(new KeyValue("63", "63、变味的鸡蛋"));
		MENU_List.add(new KeyValue("64", "64、扁鹊的医术"));
		MENU_List.add(new KeyValue("65", "65、保密"));
		MENU_List.add(new KeyValue("66", "66、落水者"));
		MENU_List.add(new KeyValue("67", "67、两手空空"));
		MENU_List.add(new KeyValue("68", "68、林肯的独断"));
		MENU_List.add(new KeyValue("69", "69、富兰克林的搏斗"));
		MENU_List.add(new KeyValue("70", "70、1850次拒绝"));
		MENU_List.add(new KeyValue("71", "71、11岁的比尔?盖茨缘何成就这桩奇事"));
		MENU_List.add(new KeyValue("72", "72、“费米思维”的启示"));
		MENU_List.add(new KeyValue("73", "73、先退一步，再往前跳"));
		MENU_List.add(new KeyValue("74", "74、“QQ之父”和他演绎的“中国梦”"));
		MENU_List.add(new KeyValue("75", "75、你知道思想能走多远"));
		MENU_List.add(new KeyValue("76", "76、靠拉面拉出的美丽人生"));
		MENU_List.add(new KeyValue("77", "77、真爱"));
		MENU_List.add(new KeyValue("78", "78、人生的长短"));
		MENU_List.add(new KeyValue("79", "79、你与目标之间有多远"));
		MENU_List.add(new KeyValue("80", "80、四川女孩香港做倒爷"));
		MENU_List.add(new KeyValue("81", "81、只识3个字的10亿老板"));
		MENU_List.add(new KeyValue("82", "82、只识3个字的10亿老板"));
		MENU_List.add(new KeyValue("83", "83、甄荣辉：寒门虎子到亿万富翁"));
		MENU_List.add(new KeyValue("84", "84、美女CEO张毅"));
		MENU_List.add(new KeyValue("85", "85、一生做好一件事"));
		MENU_List.add(new KeyValue("86", "86、培根的醒悟"));
		MENU_List.add(new KeyValue("87", "87、饥饿的人"));
		MENU_List.add(new KeyValue("88", "88、“复活”宠物：小女子掘到人生第一桶金"));
		MENU_List.add(new KeyValue("89", "89、我还有一颗感恩的心"));
		MENU_List.add(new KeyValue("90", "90、细节"));
		MENU_List.add(new KeyValue("91", "91、东方“女超人”周凯旋"));
		MENU_List.add(new KeyValue("92", "92、用比自己更优秀的人"));
		MENU_List.add(new KeyValue("93", "93、枣核能帮尖底罐"));
		MENU_List.add(new KeyValue("94", "94、财富智慧"));
		MENU_List.add(new KeyValue("95", "95、只要你想……"));
		MENU_List.add(new KeyValue("96", "96、轿夫的快乐"));
		MENU_List.add(new KeyValue("97", "97、人生可贵“退堂鼓”"));
		MENU_List.add(new KeyValue("98", "98、潜质，有点像侦探"));
		MENU_List.add(new KeyValue("99", "99、挖掘赵本山"));
		MENU_List.add(new KeyValue("100", "100、马克?吐温的计谋"));
		MENU_List.add(new KeyValue("101", "101、适合自己的鞋"));
		MENU_List.add(new KeyValue("102", "102、牛顿的黑匣子"));
		MENU_List.add(new KeyValue("103", "103、人生风湿症"));
		MENU_List.add(new KeyValue("104", "104、快乐即成功"));
		MENU_List.add(new KeyValue("105", "105、钢笔的来历"));
		MENU_List.add(new KeyValue("106", "106、奇特的墓碑"));
		MENU_List.add(new KeyValue("107", "107、我为什么不能借钱给你"));
		MENU_List.add(new KeyValue("108", "108、感谢羞辱"));
		MENU_List.add(new KeyValue("109", "109、真正的原谅"));
		MENU_List.add(new KeyValue("110", "110、心灵释荷"));
		MENU_List.add(new KeyValue("111", "111、让我当个句号吧"));
		MENU_List.add(new KeyValue("112", "112、她付给了盖茨一美元的报酬"));
		MENU_List.add(new KeyValue("113", "113、深坑和高空"));
		MENU_List.add(new KeyValue("114", "114、另一种善意"));
		MENU_List.add(new KeyValue("115", "115、小泽征尔夺魁"));
		MENU_List.add(new KeyValue("116", "116、鲍威尔的成功"));
		MENU_List.add(new KeyValue("117", "117、林肯的“马蝇术”"));
		MENU_List.add(new KeyValue("118", "118、梦想的凳子"));
		MENU_List.add(new KeyValue("119", "119、拿破仑巧借“泄密”而“保密”"));
		MENU_List.add(new KeyValue("120", "120、虚荣就是三把石灰"));
		MENU_List.add(new KeyValue("121", "121、我叫托马斯．杰斐逊"));
		MENU_List.add(new KeyValue("122", "122、不能等待的事"));
		MENU_List.add(new KeyValue("123", "123、呼吸之间"));
		MENU_List.add(new KeyValue("124", "124、让我试试"));
		MENU_List.add(new KeyValue("125", "125、自己是自己的镜子"));
		MENU_List.add(new KeyValue("126", "126、天才的遗憾"));
		MENU_List.add(new KeyValue("127", "127、哪怕仅是一点微光"));
		MENU_List.add(new KeyValue("128", "128、对女人绝妙的恭维"));
		MENU_List.add(new KeyValue("129", "129、大错误和小错误"));
		MENU_List.add(new KeyValue("130", "130、让我试试"));
		MENU_List.add(new KeyValue("131", "131、巴西总统的第一任老师"));
		MENU_List.add(new KeyValue("132", "132、坚持"));
		MENU_List.add(new KeyValue("133", "133、成功的失败者"));
		MENU_List.add(new KeyValue("134", "134、不要让瑕疵影响一生"));
		MENU_List.add(new KeyValue("135", "135、耳朵结了茧子"));
		MENU_List.add(new KeyValue("136", "136、英国首相如何说“不”"));
		MENU_List.add(new KeyValue("137", "137、胡佛上当"));
		MENU_List.add(new KeyValue("138", "138、识人"));
		MENU_List.add(new KeyValue("139", "139、最深的感悟"));
		MENU_List.add(new KeyValue("140", "140、高尔基的谎言"));
		MENU_List.add(new KeyValue("141", "141、上坡下坡"));
		MENU_List.add(new KeyValue("142", "142、最危险的经历"));
		MENU_List.add(new KeyValue("143", "143、这就是宽容"));
		MENU_List.add(new KeyValue("144", "144、韦勃斯脱和土拨鼠"));
		MENU_List.add(new KeyValue("145", "145、里根的鞋"));
		MENU_List.add(new KeyValue("146", "146、伊壁鸠鲁论无神"));
		MENU_List.add(new KeyValue("147", "147、你要一双鞋子，给你一双袜子"));
		MENU_List.add(new KeyValue("148", "148、两个女人，两样人生"));
		MENU_List.add(new KeyValue("149", "149、受益终生的举动"));
		MENU_List.add(new KeyValue("150", "150、电话里的单口相声"));
		MENU_List.add(new KeyValue("151", "151、不请求原谅"));
		MENU_List.add(new KeyValue("152", "152、少年萨达姆的求学路"));
		MENU_List.add(new KeyValue("153", "153、这就是克迪"));
		MENU_List.add(new KeyValue("154", "154、跟踪卷毛狗的人"));
		MENU_List.add(new KeyValue("155", "155、４４份爱心晚报"));
		MENU_List.add(new KeyValue("156", "156、你可以拥抱我吗？"));
		MENU_List.add(new KeyValue("157", "157、西点军校的幽默"));
		MENU_List.add(new KeyValue("158", "158、我带手电了"));
		MENU_List.add(new KeyValue("159", "159、击在餐桌上的那一拳"));
		MENU_List.add(new KeyValue("160", "160、欣赏苦难是一种愧"));
		MENU_List.add(new KeyValue("161", "161、一次非正常散步"));
		MENU_List.add(new KeyValue("162", "162、人人面前都有一根栏杆"));
		MENU_List.add(new KeyValue("163", "163、拒绝的智能"));
		MENU_List.add(new KeyValue("164", "164、宽容比自由更重要"));
		MENU_List.add(new KeyValue("165", "165、老舍欲爱不能"));
		MENU_List.add(new KeyValue("166", "166、我宁愿"));
		MENU_List.add(new KeyValue("167", "167、爱过已好"));
		MENU_List.add(new KeyValue("168", "168、格尔尼卡"));
		MENU_List.add(new KeyValue("169", "169、天使爱“美丽”"));
		MENU_List.add(new KeyValue("170", "170、被恭维者支配"));
		MENU_List.add(new KeyValue("171", "171、“卑微”是人生的第一课"));
		MENU_List.add(new KeyValue("172", "172、宽容"));
		MENU_List.add(new KeyValue("173", "173、较真儿的“自洁薄膜”"));
		MENU_List.add(new KeyValue("174", "174、海王星的发现"));
		MENU_List.add(new KeyValue("175", "175、萨科齐的退避"));
		MENU_List.add(new KeyValue("176", "176、查韦斯的半小时"));
		MENU_List.add(new KeyValue("177", "177、只成功“一点”"));
		MENU_List.add(new KeyValue("178", "178、站出来的总统"));
		MENU_List.add(new KeyValue("179", "179、作家偷钱释心理"));
		MENU_List.add(new KeyValue("180", "180、时间的光线"));
		MENU_List.add(new KeyValue("181", "181、还能干什么？"));
		MENU_List.add(new KeyValue("182", "182、林璎的越战纪念碑"));
		MENU_List.add(new KeyValue("183", "183、为新生命的诞生而飞翔"));
		MENU_List.add(new KeyValue("184", "184、说话"));
		MENU_List.add(new KeyValue("185", "185、不带着怒气做任何事"));
		MENU_List.add(new KeyValue("186", "186、苏秦的无间道"));
		MENU_List.add(new KeyValue("187", "187、１％成就１００％"));
		MENU_List.add(new KeyValue("188", "188、自己的真相"));
		MENU_List.add(new KeyValue("189", "189、人生的“配额”"));
		MENU_List.add(new KeyValue("190", "190、养活一团春意思，撑起两根穷骨头"));
		MENU_List.add(new KeyValue("191", "191、只想陪你坐一坐"));
		MENU_List.add(new KeyValue("192", "192、恰到好处的掌声"));
		MENU_List.add(new KeyValue("193", "193、爱因斯坦求职记"));
		MENU_List.add(new KeyValue("194", "194、换一种方式离成功更近"));
	}



	/** Called when the activity is first created. */
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.main);
		menuList = (ListView) findViewById(R.id.menuList);
		menuAdapter = new ArrayAdapter<KeyValue>(this,
				R.layout.simple_list_layout, R.id.txtListItem, MENU_List);
		menuList.setAdapter(menuAdapter);
		menuList.setOnItemClickListener(new OnItemClickListener() {
			public void onItemClick(AdapterView<?> arg0, View arg1, int pos,
					long id) {
				KeyValue menu = (KeyValue) arg0.getItemAtPosition(pos);
				Intent intent = new Intent();
				intent.setClass(MainActivity.this, DetailActivity.class);
				Bundle bundle = new Bundle();
				bundle.putString("menu", menu.getKey());
				bundle.putBoolean("startByMenu", true);
				intent.putExtras(bundle);
				startActivity(intent);
				finish();
			}
		});
	}
}