--==============================================================
-- DBMS name:      IBM DB2 UDB 7.x Common Server
-- Created on:     2006-9-5 10:21:41
--==============================================================


--==============================================================
-- Table: "DLOG_ALBUM"
--==============================================================
CREATE TABLE "DLOG_ALBUM"
(
   "ALBUM_ID"           NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "PHOTO_ID"           NUMERIC(6, 0),
   "DLO_ALBUM_ID"       NUMERIC(6, 0),
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "DLOG_TYPE_ID"       NUMERIC(6, 0),
   "ALBUM_NAME"         VARCHAR(40)            NOT NULL,
   "ALBUM_DESC"         VARCHAR(200),
   "PHOTO_COUNT"        INTEGER                NOT NULL,
   "ALBUM_TYPE"         INTEGER                NOT NULL,
   "VERIFYCODE"         VARCHAR(20),
   "SORT_ORDER"         INTEGER                NOT NULL,
   "CREATE_TIME"        DATE                   NOT NULL
);

--==============================================================
-- Table: "DLOG_BLOCKED_IP"
--==============================================================
CREATE TABLE "DLOG_BLOCKED_IP"
(
   "BLOCKED_IP_ID"      NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0),
   "IP_ADDR"            INTEGER                NOT NULL,
   "S_IP_ADDR"          VARCHAR(16)            NOT NULL,
   "IP_MASK"            INTEGER                NOT NULL,
   "S_IP_MASK"          VARCHAR(16)            NOT NULL,
   "BLOCKED_TYPE"       SMALLINT               NOT NULL,
   "BLOCKED_TIME"       DATE                   NOT NULL,
   "STATUS"             SMALLINT               NOT NULL
);

--==============================================================
-- Table: "DLOG_BOOKMARK"
--==============================================================
CREATE TABLE "DLOG_BOOKMARK"
(
   "MARK_ID"            NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "USERID"             NUMERIC(6, 0)          NOT NULL,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "PARENT_ID"          INTEGER                NOT NULL,
   "PARENT_TYPE"        SMALLINT               NOT NULL,
   "TITLE"              VARCHAR(200),
   "URL"                VARCHAR(200),
   "CREATE_TIME"        DATE                   NOT NULL
);

--==============================================================
-- Table: "DLOG_BULLETIN"
--==============================================================
CREATE TABLE "DLOG_BULLETIN"
(
   "BULLETIN_ID"        NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "BULLETIN_TYPE"      INTEGER                NOT NULL,
   "PUB_TIME"           DATE                   NOT NULL,
   "STATUS"             SMALLINT               NOT NULL,
   "TITLE"              VARCHAR(200)           NOT NULL,
   "CONTENT"            LONG VARCHAR           NOT NULL
);

--==============================================================
-- Table: "DLOG_CATALOG"
--==============================================================
CREATE TABLE "DLOG_CATALOG"
(
   "CATALOG_ID"         NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "DLOG_TYPE_ID"       NUMERIC(6, 0),
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "CATALOG_NAME"       VARCHAR(20)            NOT NULL,
   "CATALOG_DESC"       VARCHAR(200),
   "CREATE_TIME"        DATE                   NOT NULL,
   "ARTICLE_COUNT"      INTEGER                NOT NULL,
   "CATALOG_TYPE"       SMALLINT               NOT NULL,
   "VERIFYCODE"         VARCHAR(20),
   "SORT_ORDER"         INTEGER                NOT NULL
);

--==============================================================
-- Table: "DLOG_CATALOG_PERM"
--==============================================================
CREATE TABLE "DLOG_CATALOG_PERM"
(
   "CATALOG_ID"         NUMERIC(6, 0)          NOT NULL,
   "USERID"             NUMERIC(6, 0)          NOT NULL,
   "USER_ROLE"          INTEGER                NOT NULL
);

--==============================================================
-- Table: "DLOG_COMMENTS"
--==============================================================
CREATE TABLE "DLOG_COMMENTS"
(
   "COMMENT_ID"         NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "DLO_COMMENT_ID"     NUMERIC(6, 0),
   "SITE_ID"            NUMERIC(6, 0),
   "ENTITY_ID"          INTEGER                NOT NULL,
   "ENTITY_TYPE"        INTEGER                NOT NULL,
   "CLIENT_IP"          VARCHAR(16)            NOT NULL,
   "CLIENT_TYPE"        SMALLINT               NOT NULL,
   "CLIENT_USER_AGENT"  VARCHAR(100),
   "AUTHOR_ID"          INTEGER                NOT NULL,
   "AUTHOR"             VARCHAR(20)            NOT NULL,
   "AUTHOR_EMAIL"       VARCHAR(50),
   "AUTHOR_URL"         VARCHAR(100),
   "TITLE"              VARCHAR(200)           NOT NULL,
   "CONTENT"            LONG VARCHAR           NOT NULL,
   "CONTENT_FORMAT"     SMALLINT               NOT NULL,
   "COMMENT_TIME"       DATE                   NOT NULL,
   "COMMENT_FLAG"       SMALLINT               NOT NULL,
   "COMMENT_STATUS"     SMALLINT               NOT NULL
);

--==============================================================
-- Table: "DLOG_CONFIG"
--==============================================================
CREATE TABLE "DLOG_CONFIG"
(
   "CONFIG_ID"          NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0),
   "CONFIG_NAME"        VARCHAR(20)            NOT NULL,
   "INT_VALUE"          INTEGER,
   "STRING_VALUE"       VARCHAR(100),
   "DATE_VALUE"         DATE,
   "TIME_VALUE"         TIME,
   "TIMESTAMP_VALUE"    DATE,
   "LAST_UPDATE"        TIMESTAMP              NOT NULL
);

--==============================================================
-- Table: "DLOG_DIARY"
--==============================================================
CREATE TABLE "DLOG_DIARY"
(
   "DIARY_ID"           NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "USERID"             NUMERIC(6, 0)          NOT NULL,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "CATALOG_ID"         NUMERIC(6, 0)          NOT NULL,
   "AUTHOR"             VARCHAR(20)            NOT NULL,
   "AUTHOR_URL"         VARCHAR(100),
   "TITLE"              VARCHAR(200)           NOT NULL,
   "CONTENT"            LONG VARCHAR           NOT NULL,
   "DIARY_SIZE"         INTEGER                NOT NULL,
   "REFER"              VARCHAR(100),
   "WEATHER"            VARCHAR(20)            NOT NULL,
   "MOOD_LEVEL"         SMALLINT               NOT NULL,
   "TAGS"               VARCHAR(100),
   "BGSOUND"            INTEGER,
   "REPLY_COUNT"        INTEGER                NOT NULL,
   "VIEW_COUNT"         INTEGER                NOT NULL,
   "TB_COUNT"           INTEGER                NOT NULL,
   "CLIENT_TYPE"        SMALLINT               NOT NULL,
   "CLIENT_IP"          VARCHAR(16)            NOT NULL,
   "CLIENT_USER_AGENT"  VARCHAR(100),
   "WRITE_TIME"         DATE                   NOT NULL,
   "LAST_READ_TIME"     DATE,
   "LAST_REPLY_TIME"    DATE,
   "MODIFY_TIME"        DATE,
   "REPLY_NOTIFY"       SMALLINT               NOT NULL,
   "DIARY_TYPE"         SMALLINT               NOT NULL,
   "LOCKED"             SMALLINT               NOT NULL,
   "STATUS"             SMALLINT               NOT NULL
);

--==============================================================
-- Table: "DLOG_EXTERNAL_REFER"
--==============================================================
CREATE TABLE "DLOG_EXTERNAL_REFER"
(
   "REFER_ID"           NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0),
   "REF_ID"             INTEGER                NOT NULL,
   "REF_TYPE"           SMALLINT               NOT NULL,
   "REFER_HOST"         VARCHAR(50),
   "REFER_URL"          VARCHAR(250)           NOT NULL,
   "CLIENT_IP"          VARCHAR(16)            NOT NULL,
   "REFER_TIME"         DATE                   NOT NULL
);

--==============================================================
-- Table: "DLOG_FCK_UPLOAD_FILE"
--==============================================================
CREATE TABLE "DLOG_FCK_UPLOAD_FILE"
(
   "FCK_FILE_ID"        NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "USERID"             NUMERIC(6, 0)          NOT NULL,
   "SITE_ID"            NUMERIC(6, 0),
   "UPLOAD_TIME"        DATE                   NOT NULL,
   "SESSION_ID"         VARCHAR(100)           NOT NULL,
   "REF_ID"             INTEGER                NOT NULL,
   "REF_TYPE"           SMALLINT               NOT NULL,
   "SAVE_PATH"          VARCHAR(255)           NOT NULL,
   "FILE_URI"           VARCHAR(100)           NOT NULL,
   "FILE_TYPE"          INTEGER                NOT NULL,
   "FILE_SIZE"          INTEGER                NOT NULL
);

--==============================================================
-- Table: "DLOG_FORUM"
--==============================================================
CREATE TABLE "DLOG_FORUM"
(
   "FORUM_ID"           NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "DLOG_TYPE_ID"       NUMERIC(6, 0),
   "FORUM_NAME"         VARCHAR(40)            NOT NULL,
   "FORUM_DESC"         VARCHAR(200),
   "FORUM_TYPE"         INTEGER                NOT NULL,
   "CREATE_TIME"        DATE                   NOT NULL,
   "MODIFY_TIME"        DATE,
   "LAST_TIME"          DATE,
   "LAST_USER_ID"       INTEGER,
   "LAST_USER_NAME"     VARCHAR(50),
   "LAST_TOPIC_ID"      INTEGER,
   "SORT_ORDER"         INTEGER                NOT NULL,
   "TOPIC_COUNT"        INTEGER                NOT NULL,
   "FORUM_OPTION"       INTEGER                NOT NULL,
   "STATUS"             SMALLINT               NOT NULL
);

--==============================================================
-- Table: "DLOG_FRIEND"
--==============================================================
CREATE TABLE "DLOG_FRIEND"
(
   "USER_ID"            INTEGER                NOT NULL,
   "FRIEND_ID"          INTEGER                NOT NULL,
   "FRIEND_TYPE"        INTEGER                NOT NULL,
   "FRIEND_ROLE"        INTEGER                NOT NULL,
   "ADD_TIME"           DATE                   NOT NULL
);

--==============================================================
-- Table: "DLOG_GUESTBOOK"
--==============================================================
CREATE TABLE "DLOG_GUESTBOOK"
(
   "GUEST_BOOK_ID"      NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "USERID"             NUMERIC(6, 0)          NOT NULL,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "CONTENT"            LONG VARCHAR           NOT NULL,
   "CLIENT_TYPE"        SMALLINT               NOT NULL,
   "CLIENT_IP"          VARCHAR(16)            NOT NULL,
   "CLIENT_USER_AGENT"  VARCHAR(100),
   "CREATE_TIME"        DATE                   NOT NULL,
   "REPLY_CONTENT"      LONG VARCHAR,
   "REPLY_TIME"         DATE
);

--==============================================================
-- Table: "DLOG_J_REPLY"
--==============================================================
CREATE TABLE "DLOG_J_REPLY"
(
   "J_REPLY_ID"         NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "USERID"             NUMERIC(6, 0),
   "DIARY_ID"           NUMERIC(6, 0)          NOT NULL,
   "AUTHOR"             VARCHAR(20)            NOT NULL,
   "AUTHOR_URL"         VARCHAR(100),
   "AUTHOR_EMAIL"       VARCHAR(50),
   "CLIENT_TYPE"        SMALLINT               NOT NULL,
   "CLIENT_IP"          VARCHAR(16)            NOT NULL,
   "CLIENT_USER_AGENT"  VARCHAR(100),
   "OWNER_ONLY"         INTEGER                NOT NULL,
   "CONTENT"            LONG VARCHAR           NOT NULL,
   "WRITE_TIME"         DATE                   NOT NULL,
   "STATUS"             SMALLINT               NOT NULL
);

--==============================================================
-- Table: "DLOG_LINK"
--==============================================================
CREATE TABLE "DLOG_LINK"
(
   "LINKID"             NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "LINK_TITLE"         VARCHAR(40)            NOT NULL,
   "LINK_URL"           VARCHAR(200)           NOT NULL,
   "LINK_TYPE"          SMALLINT               NOT NULL,
   "SORT_ORDER"         INTEGER                NOT NULL,
   "CREATE_TIME"        DATE                   NOT NULL,
   "STATUS"             SMALLINT               NOT NULL
);

--==============================================================
-- Table: "DLOG_MESSAGE"
--==============================================================
CREATE TABLE "DLOG_MESSAGE"
(
   "MSGID"              NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "USERID"             NUMERIC(6, 0),
   "FROM_USER_ID"       INTEGER                NOT NULL,
   "CONTENT"            LONG VARCHAR           NOT NULL,
   "SEND_TIME"          DATE                   NOT NULL,
   "EXPIRE_TIME"        DATE,
   "READ_TIME"          DATE,
   "STATUS"             SMALLINT               NOT NULL
);

--==============================================================
-- Table: "DLOG_MUSIC"
--==============================================================
CREATE TABLE "DLOG_MUSIC"
(
   "MUSIC_ID"           NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "MUSIC_BOX_ID"       NUMERIC(6, 0),
   "USERID"             NUMERIC(6, 0),
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "MUSIC_TITLE"        VARCHAR(100)           NOT NULL,
   "MUSIC_WORD"         LONG VARCHAR,
   "ALBUM"              VARCHAR(100),
   "SINGER"             VARCHAR(50),
   "URL"                VARCHAR(200),
   "CREATE_TIME"        DATE                   NOT NULL,
   "VIEW_COUNT"         INTEGER                NOT NULL,
   "MUSIC_TYPE"         INTEGER                NOT NULL,
   "STATUS"             SMALLINT               NOT NULL
);

--==============================================================
-- Table: "DLOG_MUSICBOX"
--==============================================================
CREATE TABLE "DLOG_MUSICBOX"
(
   "MUSIC_BOX_ID"       NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "BOX_NAME"           VARCHAR(40)            NOT NULL,
   "BOX_DESC"           VARCHAR(100),
   "MUSIC_COUNT"        INTEGER                NOT NULL,
   "CREATE_TIME"        DATE                   NOT NULL,
   "SORT_ORDER"         INTEGER                NOT NULL
);

--==============================================================
-- Table: "DLOG_MY_BLACKLIST"
--==============================================================
CREATE TABLE "DLOG_MY_BLACKLIST"
(
   "MY_USER_ID"         INTEGER                NOT NULL,
   "OTHER_USER_ID"      INTEGER                NOT NULL,
   "BL_TYPE"            INTEGER                NOT NULL,
   "ADD_TIME"           DATE                   NOT NULL
);

--==============================================================
-- Table: "DLOG_P_REPLY"
--==============================================================
CREATE TABLE "DLOG_P_REPLY"
(
   "P_REPLY_ID"         NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "PHOTO_ID"           NUMERIC(6, 0)          NOT NULL,
   "USERID"             NUMERIC(6, 0),
   "AUTHOR"             VARCHAR(20)            NOT NULL,
   "AUTHOR_URL"         VARCHAR(100),
   "AUTHOR_EMAIL"       VARCHAR(50),
   "CLIENT_TYPE"        SMALLINT               NOT NULL,
   "CLIENT_IP"          VARCHAR(16)            NOT NULL,
   "CLIENT_USER_AGENT"  VARCHAR(100),
   "OWNER_ONLY"         INTEGER                NOT NULL,
   "CONTENT"            LONG VARCHAR           NOT NULL,
   "WRITE_TIME"         DATE                   NOT NULL,
   "STATUS"             SMALLINT               NOT NULL
);

--==============================================================
-- Table: "DLOG_PHOTO"
--==============================================================
CREATE TABLE "DLOG_PHOTO"
(
   "PHOTO_ID"           NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "ALBUM_ID"           NUMERIC(6, 0)          NOT NULL,
   "USERID"             NUMERIC(6, 0)          NOT NULL,
   "PHOTO_NAME"         VARCHAR(40)            NOT NULL,
   "PHOTO_DESC"         LONG VARCHAR,
   "FILE_NAME"          VARCHAR(100)           NOT NULL,
   "PHOTO_URL"          VARCHAR(100)           NOT NULL,
   "PREVIEW_URL"        VARCHAR(100)           NOT NULL,
   "TAGS"               VARCHAR(100),
   "P_YEAR"             INTEGER                NOT NULL,
   "P_MONTH"            SMALLINT               NOT NULL,
   "P_DATE"             SMALLINT               NOT NULL,
   "WIDTH"              INTEGER                NOT NULL,
   "HEIGHT"             INTEGER                NOT NULL,
   "PHOTO_SIZE"         BIGINT                 NOT NULL,
   "COLOR_BIT"          INTEGER                NOT NULL,
   "EXIF_MANUFACTURER"  VARCHAR(50),
   "EXIF_MODEL"         VARCHAR(50),
   "EXIF_ISO"           INTEGER                NOT NULL,
   "EXIF_APERTURE"      VARCHAR(20),
   "EXIF_SHUTTER"       VARCHAR(20),
   "EXIF_EXPOSURE_BIAS" VARCHAR(20),
   "EXIF_EXPOSURE_TIME" VARCHAR(20),
   "EXIF_FOCAL_LENGTH"  VARCHAR(20),
   "EXIF_COLOR_SPACE"   VARCHAR(20),
   "REPLY_COUNT"        INTEGER                NOT NULL,
   "VIEW_COUNT"         INTEGER                NOT NULL,
   "CREATE_TIME"        DATE                   NOT NULL,
   "MODIFY_TIME"        DATE,
   "LAST_REPLY_TIME"    DATE,
   "PHOTO_TYPE"         INTEGER                NOT NULL,
   "LOCKED"             SMALLINT               NOT NULL,
   "PHOTO_STATUS"       SMALLINT               NOT NULL
);

--==============================================================
-- Table: "DLOG_SITE"
--==============================================================
CREATE TABLE "DLOG_SITE"
(
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "USERID"             NUMERIC(6, 0)          NOT NULL,
   "DLOG_TYPE_ID"       NUMERIC(6, 0),
   "SITE_NAME"          VARCHAR(20)            NOT NULL,
   "SITE_C_NAME"        VARCHAR(50)            NOT NULL,
   "SITE_URL"           VARCHAR(100),
   "SITE_TITLE"         VARCHAR(100),
   "SITE_DETAIL"        VARCHAR(250),
   "SITE_ICP"           VARCHAR(20),
   "SITE_LOGO"          VARCHAR(50),
   "SITE_CSS"           VARCHAR(50),
   "SITE_LAYOUT"        VARCHAR(50),
   "SITE_LANG"          VARCHAR(10),
   "SITE_FLAG"          INTEGER                NOT NULL,
   "CREATE_TIME"        DATE                   NOT NULL,
   "LAST_TIME"          DATE,
   "EXPIRED_TIME"       DATE,
   "LAST_EXP_TIME"      DATE,
   "ACCESS_MODE"        SMALLINT               NOT NULL,
   "ACCESS_CODE"        VARCHAR(50),
   "DIARY_STATUS"       SMALLINT               NOT NULL,
   "PHOTO_STATUS"       SMALLINT               NOT NULL,
   "MUSIC_STATUS"       SMALLINT               NOT NULL,
   "FORUM_STATUS"       SMALLINT               NOT NULL,
   "GUESTBOOK_STATUS"   SMALLINT               NOT NULL,
   "DIARY_CNAME"        VARCHAR(16),
   "PHOTO_CNAME"        VARCHAR(16),
   "MUSIC_CNAME"        VARCHAR(16),
   "BBS_CNAME"          VARCHAR(16),
   "GUESTBOOK_CNAME"    VARCHAR(16),
   "PHOTO_SPACE_TOTAL"  INTEGER                NOT NULL,
   "PHOTO_SPACE_USED"   INTEGER                NOT NULL,
   "DIARY_SPACE_TOTAL"  INTEGER                NOT NULL,
   "DIARY_SPACE_USED"   INTEGER                NOT NULL,
   "MEDIA_SPACE_TOTAL"  INTEGER                NOT NULL,
   "MEDIA_SPACE_USED"   INTEGER                NOT NULL,
   "SITE_TYPE"          INTEGER                NOT NULL,
   "SITE_LEVEL"         INTEGER                NOT NULL,
   "STATUS"             SMALLINT               NOT NULL
);

--==============================================================
-- Table: "DLOG_SITE_STAT"
--==============================================================
CREATE TABLE "DLOG_SITE_STAT"
(
   "SITE_STAT_ID"       NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0),
   "STAT_DATE"          INTEGER                NOT NULL,
   "UV_COUNT"           INTEGER                NOT NULL,
   "PV_COUNT"           INTEGER                NOT NULL,
   "V_SOURCE"           INTEGER                NOT NULL,
   "UPDATE_TIME"        DATE                   NOT NULL
);

--==============================================================
-- Table: "DLOG_T_REPLY"
--==============================================================
CREATE TABLE "DLOG_T_REPLY"
(
   "T_REPLY_ID"         NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "TOPIC_ID"           NUMERIC(6, 0)          NOT NULL,
   "USERID"             NUMERIC(6, 0)          NOT NULL,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "TITLE"              VARCHAR(200)           NOT NULL,
   "CONTENT"            LONG VARCHAR           NOT NULL,
   "WRITE_TIME"         DATE,
   "STATUS"             SMALLINT,
   "CLIENT_IP"          VARCHAR(16),
   "CLIENT_TYPE"        SMALLINT,
   "CLIENT_USER_AGENT"  VARCHAR(100)
);

--==============================================================
-- Table: "DLOG_TAG"
--==============================================================
CREATE TABLE "DLOG_TAG"
(
   "TAG_ID"             NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "REF_ID"             INTEGER                NOT NULL,
   "REF_TYPE"           SMALLINT               NOT NULL,
   "TAG_NAME"           VARCHAR(20)            NOT NULL
);

--==============================================================
-- Table: "DLOG_TOPIC"
--==============================================================
CREATE TABLE "DLOG_TOPIC"
(
   "TOPIC_ID"           NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0)          NOT NULL,
   "USERID"             NUMERIC(6, 0)          NOT NULL,
   "FORUM_ID"           NUMERIC(6, 0)          NOT NULL,
   "USERNAME"           VARCHAR(40)            NOT NULL,
   "CREATE_TIME"        DATE                   NOT NULL,
   "MODIFY_TIME"        DATE,
   "TITLE"              VARCHAR(200)           NOT NULL,
   "CONTENT"            LONG VARCHAR           NOT NULL,
   "TAGS"               VARCHAR(100),
   "LAST_REPLY_TIME"    DATE,
   "LAST_REPLY_ID"      INTEGER,
   "LAST_USER_ID"       INTEGER,
   "LAST_USER_NAME"     VARCHAR(50),
   "REPLY_COUNT"        INTEGER                NOT NULL,
   "VIEW_COUNT"         INTEGER                NOT NULL,
   "LOCKED"             SMALLINT               NOT NULL,
   "TOPIC_TYPE"         INTEGER                NOT NULL,
   "STATUS"             SMALLINT               NOT NULL,
   "CLIENT_TYPE"        SMALLINT               NOT NULL,
   "CLIENT_IP"          VARCHAR(16)            NOT NULL,
   "CLIENT_USER_AGENT"  VARCHAR(100)
);

--==============================================================
-- Table: "DLOG_TRACKBACK"
--==============================================================
CREATE TABLE "DLOG_TRACKBACK"
(
   "TRACK_ID"           NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "PARENT_ID"          INTEGER                NOT NULL,
   "PARENT_TYPE"        SMALLINT               NOT NULL,
   "REFURL"             VARCHAR(100)           NOT NULL,
   "TITLE"              VARCHAR(200),
   "EXCERPT"            VARCHAR(200),
   "BLOG_NAME"          VARCHAR(50)            NOT NULL,
   "REMOTE_ADDR"        CHAR(15)               NOT NULL,
   "TRACK_TIME"         DATE                   NOT NULL
);

--==============================================================
-- Table: "DLOG_TYPE"
--==============================================================
CREATE TABLE "DLOG_TYPE"
(
   "DLOG_TYPE_ID"       NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "DLO_DLOG_TYPE_ID"   NUMERIC(6, 0),
   "TYPE_NAME"          VARCHAR(20)            NOT NULL,
   "SORT_ORDER"         INTEGER                NOT NULL
);

--==============================================================
-- Table: "DLOG_USER"
--==============================================================
CREATE TABLE "DLOG_USER"
(
   "USERID"             NUMERIC(6, 0)          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "SITE_ID"            NUMERIC(6, 0),
   "OWN_SITE_ID"        INTEGER                NOT NULL,
   "USERNAME"           VARCHAR(40)            NOT NULL,
   "PASSWORD"           VARCHAR(50)            NOT NULL,
   "USER_ROLE"          INTEGER                NOT NULL,
   "NICKNAME"           VARCHAR(50)            NOT NULL,
   "SEX"                SMALLINT               NOT NULL,
   "BIRTH"              DATE,
   "EMAIL"              VARCHAR(50),
   "HOMEPAGE"           VARCHAR(50),
   "QQ"                 VARCHAR(16),
   "MSN"                VARCHAR(50),
   "MOBILE"             VARCHAR(16),
   "NATION"             VARCHAR(40),
   "PROVINCE"           VARCHAR(40),
   "CITY"               VARCHAR(40),
   "INDUSTRY"           VARCHAR(40),
   "COMPANY"            VARCHAR(80),
   "ADDRESS"            VARCHAR(200),
   "JOB"                VARCHAR(40),
   "FAX"                VARCHAR(20),
   "TEL"                VARCHAR(20),
   "ZIP"                VARCHAR(12),
   "PORTRAIT"           VARCHAR(100),
   "RESUME"             VARCHAR(200),
   "REGTIME"            DATE                   NOT NULL,
   "LAST_TIME"          DATE,
   "LAST_IP"            VARCHAR(16),
   "KEEP_DAYS"          INTEGER                NOT NULL,
   "ONLINE_STATUS"      INTEGER                NOT NULL,
   "USER_LEVEL"         INTEGER                NOT NULL,
   "STATUS"             SMALLINT               NOT NULL,
   "ARTICLE_COUNT"      INTEGER                NOT NULL,
   "ARTICLE_REPLY_COUNT" INTEGER                NOT NULL,
   "TOPIC_COUNT"        INTEGER                NOT NULL,
   "TOPIC_REPLY_COUNT"  INTEGER                NOT NULL,
   "PHOTO_COUNT"        INTEGER                NOT NULL,
   "PHOTO_REPLY_COUNT"  INTEGER                NOT NULL,
   "GUESTBOOK_COUNT"    INTEGER                NOT NULL,
   "BOOKMARK_COUNT"     INTEGER                NOT NULL
);

ALTER TABLE "DLOG_ALBUM"
   ADD CONSTRAINT "F_R_ALBUM" FOREIGN KEY ("DLO_ALBUM_ID")
      REFERENCES "DLOG_ALBUM" ("ALBUM_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_ALBUM"
   ADD CONSTRAINT "F_R_ALBUM_COVER" FOREIGN KEY ("PHOTO_ID")
      REFERENCES "DLOG_PHOTO" ("PHOTO_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_ALBUM"
   ADD CONSTRAINT "F_R_ALBUM_TYPE" FOREIGN KEY ("DLOG_TYPE_ID")
      REFERENCES "DLOG_TYPE" ("DLOG_TYPE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_ALBUM"
   ADD CONSTRAINT "F_R_SITE_ALBUM" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_BLOCKED_IP"
   ADD CONSTRAINT "F_R_SITE_BLOCKED_I" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_BOOKMARK"
   ADD CONSTRAINT "F_R_SITE_BOOKMARK" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_BOOKMARK"
   ADD CONSTRAINT "F_R_USER_MARK" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_BULLETIN"
   ADD CONSTRAINT "F_R_SITE_BULLETIN" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_CATALOG"
   ADD CONSTRAINT "F_R_CATALOG_TYPE" FOREIGN KEY ("DLOG_TYPE_ID")
      REFERENCES "DLOG_TYPE" ("DLOG_TYPE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_CATALOG"
   ADD CONSTRAINT "F_R_SITE_CATALOG" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_CATALOG_PERM"
   ADD CONSTRAINT "F_CATALOG_PERM" FOREIGN KEY ("CATALOG_ID")
      REFERENCES "DLOG_CATALOG" ("CATALOG_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_CATALOG_PERM"
   ADD CONSTRAINT "F_CATALOG_PERM2" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_COMMENTS"
   ADD CONSTRAINT "F_R_SITE_COMMENT" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_COMMENTS"
   ADD CONSTRAINT "F_R_SUB_COMMENT" FOREIGN KEY ("DLO_COMMENT_ID")
      REFERENCES "DLOG_COMMENTS" ("COMMENT_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_CONFIG"
   ADD CONSTRAINT "F_R_SITE_CONFIG" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_DIARY"
   ADD CONSTRAINT "F_R_CATALOG_DIARY" FOREIGN KEY ("CATALOG_ID")
      REFERENCES "DLOG_CATALOG" ("CATALOG_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_DIARY"
   ADD CONSTRAINT "F_R_SITE_JOURNAL" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_DIARY"
   ADD CONSTRAINT "F_R_USER_JOURNAL" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_EXTERNAL_REFER"
   ADD CONSTRAINT "F_R_SITE_REFER" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_FCK_UPLOAD_FILE"
   ADD CONSTRAINT "F_R_SITE_FILE" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_FCK_UPLOAD_FILE"
   ADD CONSTRAINT "F_R_USER_UPLOAD" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_FORUM"
   ADD CONSTRAINT "F_R_FORUM_TYPE" FOREIGN KEY ("DLOG_TYPE_ID")
      REFERENCES "DLOG_TYPE" ("DLOG_TYPE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_FORUM"
   ADD CONSTRAINT "F_R_SITE_FORUM" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_GUESTBOOK"
   ADD CONSTRAINT "F_R_SITE_GUEST" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_GUESTBOOK"
   ADD CONSTRAINT "F_R_USER_LIUYAN" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_J_REPLY"
   ADD CONSTRAINT "F_R_JOURNAL_REPLY" FOREIGN KEY ("DIARY_ID")
      REFERENCES "DLOG_DIARY" ("DIARY_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_J_REPLY"
   ADD CONSTRAINT "F_R_SITE_J_REPLY" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_J_REPLY"
   ADD CONSTRAINT "F_R_USER_J_REPLY" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_LINK"
   ADD CONSTRAINT "F_R_SITE_LINK" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_MESSAGE"
   ADD CONSTRAINT "F_R_MSG_RECEIVER" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_MUSIC"
   ADD CONSTRAINT "F_R_MUSIC_BOX" FOREIGN KEY ("MUSIC_BOX_ID")
      REFERENCES "DLOG_MUSICBOX" ("MUSIC_BOX_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_MUSIC"
   ADD CONSTRAINT "F_R_RECOMMEND" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_MUSIC"
   ADD CONSTRAINT "F_R_SITE_MUSIC" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_MUSICBOX"
   ADD CONSTRAINT "F_R_SITE_MBOX" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_P_REPLY"
   ADD CONSTRAINT "F_R_PHOTO_REPLY" FOREIGN KEY ("PHOTO_ID")
      REFERENCES "DLOG_PHOTO" ("PHOTO_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_P_REPLY"
   ADD CONSTRAINT "F_R_SITE_P_REPLY" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_P_REPLY"
   ADD CONSTRAINT "F_R_USER_P_REPLY" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_PHOTO"
   ADD CONSTRAINT "F_R_ALBUM_PHOTO" FOREIGN KEY ("ALBUM_ID")
      REFERENCES "DLOG_ALBUM" ("ALBUM_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_PHOTO"
   ADD CONSTRAINT "F_R_PHOTO_OWNER" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_PHOTO"
   ADD CONSTRAINT "F_R_SITE_PHOTO" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_SITE"
   ADD CONSTRAINT "F_R_SITE_TYPE" FOREIGN KEY ("DLOG_TYPE_ID")
      REFERENCES "DLOG_TYPE" ("DLOG_TYPE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_SITE"
   ADD CONSTRAINT "F_R_USER_SITE" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_SITE_STAT"
   ADD CONSTRAINT "F_R_SITE_STAT" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_T_REPLY"
   ADD CONSTRAINT "F_R_SITE_T_REPLY" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_T_REPLY"
   ADD CONSTRAINT "F_R_TOPIC_REPLY" FOREIGN KEY ("TOPIC_ID")
      REFERENCES "DLOG_TOPIC" ("TOPIC_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_T_REPLY"
   ADD CONSTRAINT "F_R_USER_T_REPLY" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_TAG"
   ADD CONSTRAINT "F_R_SITE_TAG" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_TOPIC"
   ADD CONSTRAINT "F_R_FORUM_TOPIC" FOREIGN KEY ("FORUM_ID")
      REFERENCES "DLOG_FORUM" ("FORUM_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_TOPIC"
   ADD CONSTRAINT "F_R_SITE_TOPIC" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_TOPIC"
   ADD CONSTRAINT "F_R_USER_TOPIC" FOREIGN KEY ("USERID")
      REFERENCES "DLOG_USER" ("USERID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_TYPE"
   ADD CONSTRAINT "F_R_SITE_TYPE_TREE" FOREIGN KEY ("DLO_DLOG_TYPE_ID")
      REFERENCES "DLOG_TYPE" ("DLOG_TYPE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "DLOG_USER"
   ADD CONSTRAINT "F_R_SITE_USER" FOREIGN KEY ("SITE_ID")
      REFERENCES "DLOG_SITE" ("SITE_ID")
      ON DELETE RESTRICT ON UPDATE RESTRICT;

