package com.cxl;

import java.util.ArrayList;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ArrayAdapter;
import android.widget.ListView;

import com.cxl.zhonghuashangxiawuqiannian.R;

public class MainActivity extends Activity {
	ListView menuList;
	ArrayAdapter<KeyValue> menuAdapter;
	public static final ArrayList<KeyValue> MENU_List = new ArrayList<KeyValue>();
	static {
		MENU_List.add(new KeyValue("0", "0、前　言"));
		MENU_List.add(new KeyValue("1", "1、开天辟地的神话"));
		MENU_List.add(new KeyValue("2", "2、钻木取火的传说"));
		MENU_List.add(new KeyValue("3", "3、黄帝战蚩尤"));
		MENU_List.add(new KeyValue("4", "4、尧舜让位"));
		MENU_List.add(new KeyValue("5", "5、大禹治水"));
		MENU_List.add(new KeyValue("6", "6、神箭手后羿"));
		MENU_List.add(new KeyValue("7", "7、商汤和伊尹"));
		MENU_List.add(new KeyValue("8", "8、盘庚迁都"));
		MENU_List.add(new KeyValue("9", "9、姜太公钓鱼"));
		MENU_List.add(new KeyValue("10", "10、奴隶倒戈"));
		MENU_List.add(new KeyValue("11", "11、周公辅成王"));
		MENU_List.add(new KeyValue("12", "12、国人暴动"));
		MENU_List.add(new KeyValue("13", "13、骊山上的烽火"));
		MENU_List.add(new KeyValue("14", "14、囚车里的人才"));
		MENU_List.add(new KeyValue("15", "15、曹刿抗击齐军"));
		MENU_List.add(new KeyValue("16", "16、齐桓公九合诸侯"));
		MENU_List.add(new KeyValue("17", "17、愚蠢的宋襄公"));
		MENU_List.add(new KeyValue("18", "18、流亡公子重耳"));
		MENU_List.add(new KeyValue("19", "19、晋文公退避三舍"));
		MENU_List.add(new KeyValue("20", "20、弦高智退秦军"));
		MENU_List.add(new KeyValue("21", "21、崤山大战"));
		MENU_List.add(new KeyValue("22", "22、一鸣惊人的楚庄王"));
		MENU_List.add(new KeyValue("23", "23、伍子胥过昭关"));
		MENU_List.add(new KeyValue("24", "24、孔子周游列国"));
		MENU_List.add(new KeyValue("25", "25、勾践卧薪尝胆"));
		MENU_List.add(new KeyValue("26", "26、范蠡和文种"));
		MENU_List.add(new KeyValue("27", "27、墨子破云梯"));
		MENU_List.add(new KeyValue("28", "28、三家瓜分晋国"));
		MENU_List.add(new KeyValue("29", "29、商鞅南门立木"));
		MENU_List.add(new KeyValue("30", "30、孙膑庞涓斗智"));
		MENU_List.add(new KeyValue("31", "31、张仪拆散联盟"));
		MENU_List.add(new KeyValue("32", "32、赵武灵王胡服骑射"));
		MENU_List.add(new KeyValue("33", "33、孟尝君的门客"));
		MENU_List.add(new KeyValue("34", "34、燕昭王求贤"));
		MENU_List.add(new KeyValue("35", "35、田单的火牛阵"));
		MENU_List.add(new KeyValue("36", "36、屈原沉江"));
		MENU_List.add(new KeyValue("37", "37、蔺相如完璧归赵"));
		MENU_List.add(new KeyValue("38", "38、廉颇负荆请罪"));
		MENU_List.add(new KeyValue("39", "39、范雎的远交近攻计"));
		MENU_List.add(new KeyValue("40", "40、纸上谈兵的赵括"));
		MENU_List.add(new KeyValue("41", "41、毛遂自荐"));
		MENU_List.add(new KeyValue("42", "42、信陵君救赵"));
		MENU_List.add(new KeyValue("43", "43、李斯谏逐客"));
		MENU_List.add(new KeyValue("44", "44、荆轲刺秦王"));
		MENU_List.add(new KeyValue("45", "45、秦王灭六国"));
		MENU_List.add(new KeyValue("46", "46、第一个皇帝――秦始皇"));
		MENU_List.add(new KeyValue("47", "47、博浪沙的铁椎"));
		MENU_List.add(new KeyValue("48", "48、沙丘的阴谋"));
		MENU_List.add(new KeyValue("49", "49、大泽乡起义"));
		MENU_List.add(new KeyValue("50", "50、刘邦和项羽"));
		MENU_List.add(new KeyValue("51", "51、巨鹿大战"));
		MENU_List.add(new KeyValue("52", "52、刘邦进咸阳"));
		MENU_List.add(new KeyValue("53", "53、鸿门宴"));
		MENU_List.add(new KeyValue("54", "54、萧何追韩信"));
		MENU_List.add(new KeyValue("55", "55、楚汉相争"));
		MENU_List.add(new KeyValue("56", "56、霸王乌江自刎"));
		MENU_List.add(new KeyValue("57", "57、大风歌"));
		MENU_List.add(new KeyValue("58", "58、白登被围"));
		MENU_List.add(new KeyValue("59", "59、白马盟"));
		MENU_List.add(new KeyValue("60", "60、萧曹两相国"));
		MENU_List.add(new KeyValue("61", "61、周勃夺军"));
		MENU_List.add(new KeyValue("62", "62、缇萦救父"));
		MENU_List.add(new KeyValue("63", "63、周亚夫的细柳营"));
		MENU_List.add(new KeyValue("64", "64、晁错削地"));
		MENU_List.add(new KeyValue("65", "65、马邑诱敌战"));
		MENU_List.add(new KeyValue("66", "66、飞将军李广"));
		MENU_List.add(new KeyValue("67", "67、卫青和霍去病"));
		MENU_List.add(new KeyValue("68", "68、张骞通西域"));
		MENU_List.add(new KeyValue("69", "69、苏武牧羊"));
		MENU_List.add(new KeyValue("70", "70、司马迁写《史记》"));
		MENU_List.add(new KeyValue("71", "71、霍光辅政"));
		MENU_List.add(new KeyValue("72", "72、王昭君出塞"));
		MENU_List.add(new KeyValue("73", "73、王莽复古改制"));
		MENU_List.add(new KeyValue("74", "74、绿林赤眉起义"));
		MENU_List.add(new KeyValue("75", "75、昆阳大战"));
		MENU_List.add(new KeyValue("76", "76、刘秀重建汉王朝"));
		MENU_List.add(new KeyValue("77", "77、硬脖子的洛阳令"));
		MENU_List.add(new KeyValue("78", "78、老当益壮的将军"));
		MENU_List.add(new KeyValue("79", "79、取经求佛像"));
		MENU_List.add(new KeyValue("80", "80、班超投笔从军"));
		MENU_List.add(new KeyValue("81", "81、张衡和地动仪"));
		MENU_List.add(new KeyValue("82", "82、跋扈将军梁冀"));
		MENU_List.add(new KeyValue("83", "83、“党锢”事件"));
		MENU_List.add(new KeyValue("84", "84、范滂进监狱"));
		MENU_List.add(new KeyValue("85", "85、黄巾军起义"));
		MENU_List.add(new KeyValue("86", "86、袁绍杀宦官"));
		MENU_List.add(new KeyValue("87", "87、曹操起兵"));
		MENU_List.add(new KeyValue("88", "88、王允计除董卓"));
		MENU_List.add(new KeyValue("89", "89、迁都许城"));
		MENU_List.add(new KeyValue("90", "90、衣带里的密诏"));
		MENU_List.add(new KeyValue("91", "91、官渡大战"));
		MENU_List.add(new KeyValue("92", "92、孙策占据江东"));
		MENU_List.add(new KeyValue("93", "93、诸葛亮隆中对策"));
		MENU_List.add(new KeyValue("94", "94、周瑜火攻赤壁"));
		MENU_List.add(new KeyValue("95", "95、华佗治病"));
		MENU_List.add(new KeyValue("96", "96、刘备进益州"));
		MENU_List.add(new KeyValue("97", "97、蔡文姬归汉"));
		MENU_List.add(new KeyValue("98", "98、关羽水淹七军"));
		MENU_List.add(new KeyValue("99", "99、吕蒙白衣渡江"));
		MENU_List.add(new KeyValue("100", "100、曹植七步成诗"));
		MENU_List.add(new KeyValue("101", "101、陆逊烧连营"));
		MENU_List.add(new KeyValue("102", "102、七擒孟获"));
		MENU_List.add(new KeyValue("103", "103、马谡失街亭"));
		MENU_List.add(new KeyValue("104", "104、五丈原"));
		MENU_List.add(new KeyValue("105", "105、司马懿装病"));
		MENU_List.add(new KeyValue("106", "106、司马昭的野心"));
		MENU_List.add(new KeyValue("107", "107、邓艾偷渡剑阁"));
		MENU_List.add(new KeyValue("108", "108、扶不起的阿斗"));
		MENU_List.add(new KeyValue("109", "109、王浚楼船破吴"));
		MENU_List.add(new KeyValue("110", "110、石崇王恺比富"));
		MENU_List.add(new KeyValue("111", "111、周处除“三害”"));
		MENU_List.add(new KeyValue("112", "112、白痴皇帝"));
		MENU_List.add(new KeyValue("113", "113、八王混战"));
		MENU_List.add(new KeyValue("114", "114、李特的流民大营"));
		MENU_List.add(new KeyValue("115", "115、匈奴人称汉帝"));
		MENU_List.add(new KeyValue("116", "116、闻鸡起舞"));
		MENU_List.add(new KeyValue("117", "117、王马共天下"));
		MENU_List.add(new KeyValue("118", "118、石勒读汉书"));
		MENU_List.add(new KeyValue("119", "119、祖逖中流击楫"));
		MENU_List.add(new KeyValue("120", "120、陶侃运砖头"));
		MENU_List.add(new KeyValue("121", "121、王羲之写字换鹅"));
		MENU_List.add(new KeyValue("122", "122、桓温北伐"));
		MENU_List.add(new KeyValue("123", "123、王猛扪虱谈天下"));
		MENU_List.add(new KeyValue("124", "124、一意孤行的苻坚"));
		MENU_List.add(new KeyValue("125", "125、谢安东山再起"));
		MENU_List.add(new KeyValue("126", "126、淝水之战"));
		MENU_List.add(new KeyValue("127", "127、陶渊明不折腰"));
		MENU_List.add(new KeyValue("128", "128、刘裕摆却月阵"));
		MENU_List.add(new KeyValue("129", "129、檀道济唱筹量沙"));
		MENU_List.add(new KeyValue("130", "130、说实话的高允"));
		MENU_List.add(new KeyValue("131", "131、大发明家祖冲之"));
		MENU_List.add(new KeyValue("132", "132、范缜反对迷信"));
		MENU_List.add(new KeyValue("133", "133、魏孝文帝改革风俗"));
		MENU_List.add(new KeyValue("134", "134、北魏的分裂"));
		MENU_List.add(new KeyValue("135", "135、梁武帝做和尚"));
		MENU_List.add(new KeyValue("136", "136、反复无常的侯景"));
		MENU_List.add(new KeyValue("137", "137、陈后主亡国"));
		MENU_List.add(new KeyValue("138", "138、赵绰依法办事"));
		MENU_List.add(new KeyValue("139", "139、隋炀帝游江都"));
		MENU_List.add(new KeyValue("140", "140、李密牛角挂书"));
		MENU_List.add(new KeyValue("141", "141、瓦岗军开仓分粮"));
		MENU_List.add(new KeyValue("142", "142、李渊太原起兵"));
		MENU_List.add(new KeyValue("143", "143、李世民取东都"));
		MENU_List.add(new KeyValue("144", "144、玄武门之变"));
		MENU_List.add(new KeyValue("145", "145、魏征直言敢谏"));
		MENU_List.add(new KeyValue("146", "146、李靖夜袭阴山"));
		MENU_List.add(new KeyValue("147", "147、玄奘和尚取经"));
		MENU_List.add(new KeyValue("148", "148、文成公主进吐蕃"));
		MENU_List.add(new KeyValue("149", "149、女皇帝武则天"));
		MENU_List.add(new KeyValue("150", "150、请君入瓮"));
		MENU_List.add(new KeyValue("151", "151、狄仁杰桃李满门"));
		MENU_List.add(new KeyValue("152", "152、张说不做伪证"));
		MENU_List.add(new KeyValue("153", "153、姚崇灭蝗"));
		MENU_List.add(new KeyValue("154", "154、口蜜腹剑的李林甫"));
		MENU_List.add(new KeyValue("155", "155、李白蔑视权贵"));
		MENU_List.add(new KeyValue("156", "156、安禄山叛乱"));
		MENU_List.add(new KeyValue("157", "157、颜杲卿骂贼"));
		MENU_List.add(new KeyValue("158", "158、马嵬驿兵变"));
		MENU_List.add(new KeyValue("159", "159、张巡草人借箭"));
		MENU_List.add(new KeyValue("160", "160、南霁云借兵"));
		MENU_List.add(new KeyValue("161", "161、李泌归山"));
		MENU_List.add(new KeyValue("162", "162、李光弼大破史思明"));
		MENU_List.add(new KeyValue("163", "163、杜甫写“诗史”"));
		MENU_List.add(new KeyValue("164", "164、段秀实不怕强暴"));
		MENU_List.add(new KeyValue("165", "165、郭子仪单骑退回纥"));
		MENU_List.add(new KeyValue("166", "166、颜真卿刚强不屈"));
		MENU_List.add(new KeyValue("167", "167、浑瑊和李晟"));
		MENU_List.add(new KeyValue("168", "168、东宫里的棋手"));
		MENU_List.add(new KeyValue("169", "169、刘禹锡游玄都观"));
		MENU_List.add(new KeyValue("170", "170、白居易进长安"));
		MENU_List.add(new KeyValue("171", "171、李塑雪夜下蔡州"));
		MENU_List.add(new KeyValue("172", "172、韩愈反对迎佛骨"));
		MENU_List.add(new KeyValue("173", "173、甘露事件"));
		MENU_List.add(new KeyValue("174", "174、朋党的争吵"));
		MENU_List.add(new KeyValue("175", "175、冲天大将军黄巢"));
		MENU_List.add(new KeyValue("176", "176、唐王朝的末日"));
		MENU_List.add(new KeyValue("177", "177、“海龙王”钱镠"));
		MENU_List.add(new KeyValue("178", "178、伶人做官"));
		MENU_List.add(new KeyValue("179", "179、“儿皇帝”石敬瑭"));
		MENU_List.add(new KeyValue("180", "180、周世宗斥冯道"));
		MENU_List.add(new KeyValue("181", "181、黄袍加身"));
		MENU_List.add(new KeyValue("182", "182、杯酒释兵权"));
		MENU_List.add(new KeyValue("183", "183、李后主亡国"));
		MENU_List.add(new KeyValue("184", "184、赵普收礼"));
		MENU_List.add(new KeyValue("185", "185、杨无敌"));
		MENU_List.add(new KeyValue("186", "186、王小波起义"));
		MENU_List.add(new KeyValue("187", "187、寇准抗辽"));
		MENU_List.add(new KeyValue("188", "188、元昊建立西夏"));
		MENU_List.add(new KeyValue("189", "189、狄青不怕出身低"));
		MENU_List.add(new KeyValue("190", "190、范仲淹实行新政"));
		MENU_List.add(new KeyValue("191", "191、欧阳修改革文风"));
		MENU_List.add(new KeyValue("192", "192、铁面无私的包拯"));
		MENU_List.add(new KeyValue("193", "193、王安石变法"));
		MENU_List.add(new KeyValue("194", "194、沈括出使"));
		MENU_List.add(new KeyValue("195", "195、司马光写《通鉴》"));
		MENU_List.add(new KeyValue("196", "196、苏东坡游赤壁"));
		MENU_List.add(new KeyValue("197", "197、花石纲"));
		MENU_List.add(new KeyValue("198", "198、方腊起义"));
		MENU_List.add(new KeyValue("199", "199、头鱼宴上的阿骨打"));
		MENU_List.add(new KeyValue("200", "200、李纲守东京"));
		MENU_List.add(new KeyValue("201", "201、太学生请愿"));
		MENU_List.add(new KeyValue("202", "202、两个皇帝当俘虏"));
		MENU_List.add(new KeyValue("203", "203、宗泽三呼“过河”"));
		MENU_List.add(new KeyValue("204", "204、女词人李清照"));
		MENU_List.add(new KeyValue("205", "205、韩世忠阻击金兵"));
		MENU_List.add(new KeyValue("206", "206、岳家军大破兀术"));
		MENU_List.add(new KeyValue("207", "207、卖国贼秦桧"));
		MENU_List.add(new KeyValue("208", "208、“莫须有”冤狱"));
		MENU_List.add(new KeyValue("209", "209、钟相杨么起义"));
		MENU_List.add(new KeyValue("210", "210、虞允文书生退敌"));
		MENU_List.add(new KeyValue("211", "211、辛弃疾活捉叛徒"));
		MENU_List.add(new KeyValue("212", "212、陆游临终留诗"));
		MENU_List.add(new KeyValue("213", "213、成吉思汗统一蒙古"));
		MENU_List.add(new KeyValue("214", "214、贾似道误国"));
		MENU_List.add(new KeyValue("215", "215、文天祥起兵"));
		MENU_List.add(new KeyValue("216", "216、张世杰死守厓山"));
		MENU_List.add(new KeyValue("217", "217、正气歌"));
		MENU_List.add(new KeyValue("218", "218、郭守敬修订历法"));
		MENU_List.add(new KeyValue("219", "219、欧洲来客马可波罗"));
		MENU_List.add(new KeyValue("220", "220、《窦娥冤》感天动地"));
		MENU_List.add(new KeyValue("221", "221、一只眼的石人"));
		MENU_List.add(new KeyValue("222", "222、和尚当元帅"));
		MENU_List.add(new KeyValue("223", "223、鄱阳湖大战"));
		MENU_List.add(new KeyValue("224", "224、刘伯温求雨"));
		MENU_List.add(new KeyValue("225", "225、胡维庸案件"));
		MENU_List.add(new KeyValue("226", "226、燕王进南京"));
		MENU_List.add(new KeyValue("227", "227、三保太监下西洋"));
		MENU_List.add(new KeyValue("228", "228、土木堡的惨败"));
		MENU_List.add(new KeyValue("229", "229、于谦保卫北京"));
		MENU_List.add(new KeyValue("230", "230、杨一清计除刘瑾"));
		MENU_List.add(new KeyValue("231", "231、杨继盛冒死劾严嵩"));
		MENU_List.add(new KeyValue("232", "232、海瑞刚正不阿"));
		MENU_List.add(new KeyValue("233", "233、戚继光驱逐倭寇"));
		MENU_List.add(new KeyValue("234", "234、李时珍上山采药"));
		MENU_List.add(new KeyValue("235", "235、张居正辅政"));
		MENU_List.add(new KeyValue("236", "236、葛贤痛打税监"));
		MENU_List.add(new KeyValue("237", "237、努尔哈赤建立后金"));
		MENU_List.add(new KeyValue("238", "238、萨尔浒大战"));
		MENU_List.add(new KeyValue("239", "239、徐光启研究西学"));
		MENU_List.add(new KeyValue("240", "240、左光斗入狱"));
		MENU_List.add(new KeyValue("241", "241、五人墓"));
		MENU_List.add(new KeyValue("242", "242、袁崇焕大战宁远"));
		MENU_List.add(new KeyValue("243", "243、皇太极施反间计"));
		MENU_List.add(new KeyValue("244", "244、徐霞客远游探险"));
		MENU_List.add(new KeyValue("245", "245、闯王李自成"));
		MENU_List.add(new KeyValue("246", "246、卢象战死巨鹿"));
		MENU_List.add(new KeyValue("247", "247、张献忠奇袭襄阳"));
		MENU_List.add(new KeyValue("248", "248、李岩和红娘子"));
		MENU_List.add(new KeyValue("249", "249、吴三桂借清兵"));
		MENU_List.add(new KeyValue("250", "250、史可法死守扬州"));
		MENU_List.add(new KeyValue("251", "251、夏完淳怒斥洪承畴"));
		MENU_List.add(new KeyValue("252", "252、郑成功收复台湾"));
		MENU_List.add(new KeyValue("253", "253、李定国转战西南"));
		MENU_List.add(new KeyValue("254", "254、康熙帝平定三藩"));
		MENU_List.add(new KeyValue("255", "255、雅克萨的胜利"));
		MENU_List.add(new KeyValue("256", "256、三征噶尔丹"));
		MENU_List.add(new KeyValue("257", "257、顾炎武著书立说"));
		MENU_List.add(new KeyValue("258", "258、文字狱"));
		MENU_List.add(new KeyValue("259", "259、乾隆帝禁书修书"));
		MENU_List.add(new KeyValue("260", "260、曹雪芹写《红楼梦》"));
		MENU_List.add(new KeyValue("261", "261、大贪官和珅"));
		MENU_List.add(new KeyValue("262", "262、女英雄王聪儿"));

	}



	/** Called when the activity is first created. */
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.main);
		menuList = (ListView) findViewById(R.id.menuList);
		menuAdapter = new ArrayAdapter<KeyValue>(this,
				R.layout.simple_list_layout, R.id.txtListItem, MENU_List);
		menuList.setAdapter(menuAdapter);
		menuList.setOnItemClickListener(new OnItemClickListener() {
			public void onItemClick(AdapterView<?> arg0, View arg1, int pos,
					long id) {
				KeyValue menu = (KeyValue) arg0.getItemAtPosition(pos);
				Intent intent = new Intent();
				intent.setClass(MainActivity.this, DetailActivity.class);
				Bundle bundle = new Bundle();
				bundle.putString("menu", menu.getKey());
				bundle.putBoolean("startByMenu", true);
				intent.putExtras(bundle);
				startActivity(intent);
				finish();
			}
		});
	}
}