package com.cxl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ListManager {

	public static final List<String> First_Menu_List = new ArrayList<String>();
	public static Map<String, List<KeyValue>> Menu_File_Map = new HashMap<String, List<KeyValue>>();
	public static List<KeyValue> AllList = new ArrayList<KeyValue>();
	public static List<KeyValue> SearchList = new ArrayList<KeyValue>();

	public static void getSearchList(String paramString) {
		if ("".equals(paramString)) {
			SearchList.clear();
			SearchList.addAll(new ArrayList<KeyValue>(AllList));
			return  ;
		}
		if (SearchList != null) {
			SearchList.clear();
		}
		for (int i = 0; i < AllList.size(); i++) {
			String content = AllList.get(i).getValue();
			if (content.indexOf(paramString) != -1) {
				SearchList.add(AllList.get(i));
			}
		}
	}

	public static final String[] groups = { "唐诗三百首", "宋词三百首", "元曲三百首" };
	// 子列表数据
	public static final String[][] children = {
			{ "五言古诗", "五言乐府", "七言古诗", "七言乐府", "五言律诗", "七言律诗", "七言乐府", "五言绝句",
					"五言乐府", "七言绝句", "七言乐府" }, { "宋词三百首" }, { "元曲三百首" } };

	static {

		List<KeyValue> list = new ArrayList<KeyValue>();

		list.add(new KeyValue("钱惟演 木兰花", "sc_001.txt"));
		list.add(new KeyValue("范仲淹 渔家傲", "sc_002.txt"));
		list.add(new KeyValue("范仲淹 苏幕遮", "sc_003.txt"));
		list.add(new KeyValue("范仲淹 御街行", "sc_004.txt"));
		list.add(new KeyValue("张先   菩萨蛮", "sc_005.txt"));
		list.add(new KeyValue("张先   千秋岁", "sc_006.txt"));
		list.add(new KeyValue("张先   一丛花", "sc_007.txt"));
		list.add(new KeyValue("张先   醉垂鞭", "sc_008.txt"));
		list.add(new KeyValue("张先   木兰花", "sc_009.txt"));
		list.add(new KeyValue("张先   天仙子", "sc_010.txt"));
		list.add(new KeyValue("张先   青门引", "sc_011.txt"));
		list.add(new KeyValue("晏殊   浣溪沙", "sc_012.txt"));
		list.add(new KeyValue("晏殊   浣溪沙", "sc_013.txt"));
		list.add(new KeyValue("晏殊   清平乐", "sc_014.txt"));
		list.add(new KeyValue("晏殊   清平乐", "sc_015.txt"));
		list.add(new KeyValue("晏殊   木兰花", "sc_016.txt"));
		list.add(new KeyValue("晏殊   木兰花", "sc_017.txt"));
		list.add(new KeyValue("晏殊   踏莎行", "sc_018.txt"));
		list.add(new KeyValue("晏殊   木兰花", "sc_019.txt"));
		list.add(new KeyValue("晏殊   踏莎行", "sc_020.txt"));
		list.add(new KeyValue("晏殊   破阵子", "sc_021.txt"));
		list.add(new KeyValue("宋祁   木兰花", "sc_022.txt"));
		list.add(new KeyValue("欧阳修 明妃曲和王介甫作", "sc_023.txt"));
		list.add(new KeyValue("欧阳修 南歌子", "sc_024.txt"));
		list.add(new KeyValue("欧阳修 踏莎行", "sc_025.txt"));
		list.add(new KeyValue("欧阳修 诉衷情", "sc_026.txt"));
		list.add(new KeyValue("欧阳修 蝶恋花", "sc_027.txt"));
		list.add(new KeyValue("欧阳修 蝶恋花", "sc_028.txt"));
		list.add(new KeyValue("欧阳修 生查子·元夕", "sc_029.txt"));
		list.add(new KeyValue("欧阳修 木兰花", "sc_030.txt"));
		list.add(new KeyValue("欧阳修 蝶恋花", "sc_031.txt"));
		list.add(new KeyValue("欧阳修 青玉案", "sc_032.txt"));
		list.add(new KeyValue("欧阳修 浪淘沙", "sc_033.txt"));
		list.add(new KeyValue("欧阳修 南歌子", "sc_034.txt"));
		list.add(new KeyValue("欧阳修 浣溪沙", "sc_035.txt"));
		list.add(new KeyValue("欧阳修 蝶恋花", "sc_036.txt"));
		list.add(new KeyValue("柳永   红窗迥", "sc_037.txt"));
		list.add(new KeyValue("柳永   曲玉管", "sc_038.txt"));
		list.add(new KeyValue("柳永   采莲令", "sc_039.txt"));
		list.add(new KeyValue("柳永   蝶恋花", "sc_040.txt"));
		list.add(new KeyValue("柳永   满江红", "sc_041.txt"));
		list.add(new KeyValue("柳永   浪淘沙慢", "sc_042.txt"));
		list.add(new KeyValue("柳永   少年游", "sc_043.txt"));
		list.add(new KeyValue("柳永   雨霖铃", "sc_044.txt"));
		list.add(new KeyValue("柳永   红窗迥", "sc_045.txt"));
		list.add(new KeyValue("柳永   定风波", "sc_046.txt"));
		list.add(new KeyValue("柳永   玉蝴蝶", "sc_047.txt"));
		list.add(new KeyValue("柳永   迷神引", "sc_048.txt"));
		list.add(new KeyValue("柳永   八声甘州", "sc_049.txt"));
		list.add(new KeyValue("韩缜   凤箫吟", "sc_050.txt"));
		list.add(new KeyValue("王安石 千秋岁引", "sc_051.txt"));
		list.add(new KeyValue("王安石 桂枝香", "sc_052.txt"));
		list.add(new KeyValue("王安国 清平乐", "sc_053.txt"));
		list.add(new KeyValue("晏几道 蝶恋花", "sc_054.txt"));
		list.add(new KeyValue("晏几道 蝶恋花", "sc_055.txt"));
		list.add(new KeyValue("晏几道 鹧鸪天", "sc_056.txt"));
		list.add(new KeyValue("晏几道 生查子", "sc_057.txt"));
		list.add(new KeyValue("晏几道 六幺令", "sc_058.txt"));
		list.add(new KeyValue("晏几道 玉楼春", "sc_059.txt"));
		list.add(new KeyValue("晏几道 清平乐", "sc_061.txt"));
		list.add(new KeyValue("晏几道 木兰花", "sc_062.txt"));
		list.add(new KeyValue("晏几道 留春令", "sc_063.txt"));
		list.add(new KeyValue("晏几道 御街行", "sc_064.txt"));
		list.add(new KeyValue("晏几道 阮郎归", "sc_065.txt"));
		list.add(new KeyValue("晏几道 阮郎归", "sc_066.txt"));
		list.add(new KeyValue("晏几道 虞美人", "sc_067.txt"));
		list.add(new KeyValue("晏几道 思远人", "sc_068.txt"));
		list.add(new KeyValue("晏几道 采桑子", "sc_069.txt"));
		list.add(new KeyValue("晏几道 少年游", "sc_070.txt"));
		list.add(new KeyValue("王观   卜算子·送鲍浩然之浙东", "sc_071.txt"));
		list.add(new KeyValue("王观   庆清朝慢·踏青", "sc_072.txt"));
		list.add(new KeyValue("苏轼   鹧鸪天", "sc_073.txt"));
		list.add(new KeyValue("苏轼   江城子·密州出猎", "sc_074.txt"));
		list.add(new KeyValue("苏轼   浣溪沙徐门石潭谢雨道上作，五首", "sc_075.txt"));
		list.add(new KeyValue("苏轼   水调歌头(丙辰中秋，欢饮达旦，大醉作此篇，兼怀子由。)", "sc_076.txt"));
		list.add(new KeyValue("苏轼   水龙吟", "sc_077.txt"));
		list.add(new KeyValue("苏轼   永遇乐", "sc_078.txt"));
		list.add(new KeyValue("苏轼   卜算子", "sc_079.txt"));
		list.add(new KeyValue("苏轼   洞仙歌", "sc_080.txt"));
		list.add(new KeyValue("苏轼   青玉案", "sc_081.txt"));
		list.add(new KeyValue("苏轼   定风波", "sc_082.txt"));
		list.add(new KeyValue("苏轼   临江仙", "sc_083.txt"));
		list.add(new KeyValue("苏轼   江城子", "sc_084.txt"));
		list.add(new KeyValue("苏轼   水调歌头", "sc_085.txt"));
		list.add(new KeyValue("苏轼   蝶恋花", "sc_086.txt"));
		list.add(new KeyValue("苏轼   西江月", "sc_087.txt"));
		list.add(new KeyValue("苏轼   念奴娇·赤壁怀古", "sc_088.txt"));
		list.add(new KeyValue("黄庭坚 水调歌头", "sc_089.txt"));
		list.add(new KeyValue("黄庭坚 望江东", "sc_090.txt"));
		list.add(new KeyValue("李之仪 卜算子", "sc_091.txt"));
		list.add(new KeyValue("李之仪 谢池春", "sc_092.txt"));
		list.add(new KeyValue("舒亶   虞美人", "sc_093.txt"));
		list.add(new KeyValue("晁元礼 绿头鸭", "sc_094.txt"));
		list.add(new KeyValue("李元膺 洞仙歌", "sc_095.txt"));
		list.add(new KeyValue("朱服   渔家傲", "sc_096.txt"));
		list.add(new KeyValue("时彦   青门饮", "sc_097.txt"));
		list.add(new KeyValue("秦观   如梦令·春景", "sc_098.txt"));
		list.add(new KeyValue("秦观   八六子", "sc_099.txt"));
		list.add(new KeyValue("秦观   满庭芳", "sc_100.txt"));
		list.add(new KeyValue("秦观   满庭芳", "sc_101.txt"));
		list.add(new KeyValue("秦观   浣溪沙", "sc_102.txt"));
		list.add(new KeyValue("秦观   减字木兰花", "sc_103.txt"));
		list.add(new KeyValue("秦观   阮郎归", "sc_104.txt"));
		list.add(new KeyValue("秦观   鹊桥仙", "sc_105.txt"));
		list.add(new KeyValue("秦观   江城子", "sc_106.txt"));
		list.add(new KeyValue("秦观   如梦令", "sc_107.txt"));
		list.add(new KeyValue("秦观   望海潮", "sc_108.txt"));
		list.add(new KeyValue("李甲   帝台春", "sc_109.txt"));
		list.add(new KeyValue("贺铸   石州慢", "sc_110.txt"));
		list.add(new KeyValue("贺铸   青玉案", "sc_111.txt"));
		list.add(new KeyValue("贺铸   石州慢", "sc_112.txt"));
		list.add(new KeyValue("贺铸   感皇恩", "sc_113.txt"));
		list.add(new KeyValue("贺铸   浣溪沙", "sc_114.txt"));
		list.add(new KeyValue("贺铸   天门谣", "sc_115.txt"));
		list.add(new KeyValue("贺铸   浣溪沙", "sc_116.txt"));
		list.add(new KeyValue("贺铸   忆秦娥", "sc_117.txt"));
		list.add(new KeyValue("贺铸   蝶恋花", "sc_118.txt"));
		list.add(new KeyValue("贺铸   天香", "sc_119.txt"));
		list.add(new KeyValue("贺铸   踏莎行", "sc_120.txt"));
		list.add(new KeyValue("晁补之 水龙吟", "sc_121.txt"));
		list.add(new KeyValue("晁补之 盐角儿·毫社观梅", "sc_122.txt"));
		list.add(new KeyValue("晁补之 洞仙歌·泗州中秋作", "sc_123.txt"));
		list.add(new KeyValue("晁补之 忆少年·别历下", "sc_124.txt"));
		list.add(new KeyValue("毛滂   惜分飞", "sc_125.txt"));
		list.add(new KeyValue("晁冲之 临江仙", "sc_126.txt"));
		list.add(new KeyValue("叶梦得 贺新郎", "sc_127.txt"));
		list.add(new KeyValue("叶梦得 虞美人", "sc_128.txt"));
		list.add(new KeyValue("刘一止 喜迁莺·晓行", "sc_129.txt"));
		list.add(new KeyValue("汪藻   点绛唇", "sc_130.txt"));
		list.add(new KeyValue("曹组   蓦山溪·梅", "sc_131.txt"));
		list.add(new KeyValue("李邴   汉宫春", "sc_132.txt"));
		list.add(new KeyValue("徐伸   转调二郎神", "sc_133.txt"));
		list.add(new KeyValue("田为   江神子慢", "sc_134.txt"));
		list.add(new KeyValue("万俟咏 三台·清明应制", "sc_135.txt"));
		list.add(new KeyValue("陈克   菩萨蛮", "sc_136.txt"));
		list.add(new KeyValue("陈克   菩萨蛮", "sc_137.txt"));
		list.add(new KeyValue("周紫芝 鹧鸪天", "sc_138.txt"));
		list.add(new KeyValue("周紫芝 踏莎行", "sc_139.txt"));
		list.add(new KeyValue("徽宗皇帝 宴山亭·北行见杏花", "sc_140.txt"));
		list.add(new KeyValue("廖世美 烛影摇红·题安陆浮云楼", "sc_141.txt"));
		list.add(new KeyValue("李清照 武陵春·春晚", "sc_142.txt"));
		list.add(new KeyValue("李清照 渔家傲", "sc_143.txt"));
		list.add(new KeyValue("李清照 永遇乐", "sc_144.txt"));
		list.add(new KeyValue("李清照 如梦令", "sc_145.txt"));
		list.add(new KeyValue("李清照 凤凰台上忆吹箫", "sc_146.txt"));
		list.add(new KeyValue("李清照 醉花阴", "sc_147.txt"));
		list.add(new KeyValue("李清照 如梦令", "sc_148.txt"));
		list.add(new KeyValue("李清照 念奴娇·春情", "sc_149.txt"));
		list.add(new KeyValue("李清照 声声慢", "sc_150.txt"));
		list.add(new KeyValue("蔡伸   苏武慢", "sc_151.txt"));
		list.add(new KeyValue("蔡伸   柳梢青", "sc_152.txt"));
		list.add(new KeyValue("李重元 忆王孙", "sc_153.txt"));
		list.add(new KeyValue("李玉   贺新郎", "sc_154.txt"));
		list.add(new KeyValue("陈与义 临江仙", "sc_155.txt"));
		list.add(new KeyValue("陈与义 临江仙", "sc_156.txt"));
		list.add(new KeyValue("吕滨老 薄幸", "sc_157.txt"));
		list.add(new KeyValue("张元干 石州慢", "sc_158.txt"));
		list.add(new KeyValue("鲁逸仲 南浦", "sc_159.txt"));
		list.add(new KeyValue("岳飞   满江红", "sc_160.txt"));
		list.add(new KeyValue("韩元吉 六州歌头", "sc_161.txt"));
		list.add(new KeyValue("袁去华 剑器近", "sc_162.txt"));
		list.add(new KeyValue("袁去华 瑞鹤仙", "sc_163.txt"));
		list.add(new KeyValue("袁去华 安公子", "sc_164.txt"));
		list.add(new KeyValue("陆淞   瑞鹤仙", "sc_165.txt"));
		list.add(new KeyValue("陆游   卜算子·咏梅", "sc_166.txt"));
		list.add(new KeyValue("范成大 秦楼月", "sc_167.txt"));
		list.add(new KeyValue("范成大 眼儿媚", "sc_168.txt"));
		list.add(new KeyValue("范成大 霜天晓角", "sc_169.txt"));
		list.add(new KeyValue("范成大 鹧鸪天", "sc_170.txt"));
		list.add(new KeyValue("张孝祥 念奴娇·过洞庭", "sc_171.txt"));
		list.add(new KeyValue("张孝祥 浣溪沙", "sc_172.txt"));
		list.add(new KeyValue("程垓   水龙吟", "sc_173.txt"));
		list.add(new KeyValue("陈亮   水龙吟·春恨", "sc_174.txt"));
		list.add(new KeyValue("章良能 小重山", "sc_175.txt"));
		list.add(new KeyValue("张镃   满庭芳·促织儿", "sc_176.txt"));
		list.add(new KeyValue("张镃   宴山亭", "sc_177.txt"));
		list.add(new KeyValue("刘过   唐多令", "sc_178.txt"));
		list.add(new KeyValue("周邦彦 过秦楼", "sc_179.txt"));
		list.add(new KeyValue("周邦彦 兰陵王", "sc_180.txt"));
		list.add(new KeyValue("周邦彦 瑞龙吟", "sc_181.txt"));
		list.add(new KeyValue("周邦彦 琐窗寒", "sc_182.txt"));
		list.add(new KeyValue("周邦彦 虞美人", "sc_183.txt"));
		list.add(new KeyValue("周邦彦 兰陵王", "sc_184.txt"));
		list.add(new KeyValue("周邦彦 六丑", "sc_185.txt"));
		list.add(new KeyValue("周邦彦 夜飞鹊", "sc_186.txt"));
		list.add(new KeyValue("周邦彦 满庭芳", "sc_187.txt"));
		list.add(new KeyValue("周邦彦 过秦楼", "sc_188.txt"));
		list.add(new KeyValue("周邦彦 玉楼春", "sc_189.txt"));
		list.add(new KeyValue("周邦彦 花犯", "sc_190.txt"));
		list.add(new KeyValue("周邦彦 蝶恋花", "sc_191.txt"));
		list.add(new KeyValue("周邦彦 解连环", "sc_192.txt"));
		list.add(new KeyValue("周邦彦 大酺", "sc_193.txt"));
		list.add(new KeyValue("周邦彦 拜星月", "sc_194.txt"));
		list.add(new KeyValue("周邦彦 解语花·上元", "sc_195.txt"));
		list.add(new KeyValue("周邦彦 关河令", "sc_196.txt"));
		list.add(new KeyValue("周邦彦 绮寮怨", "sc_197.txt"));
		list.add(new KeyValue("周邦彦 尉迟杯", "sc_198.txt"));
		list.add(new KeyValue("周邦彦 瑞鹤仙", "sc_199.txt"));
		list.add(new KeyValue("周邦彦 西河·金陵怀古", "sc_200.txt"));
		list.add(new KeyValue("周邦彦 浪淘沙慢", "sc_201.txt"));
		list.add(new KeyValue("周邦彦 夜游宫", "sc_202.txt"));
		list.add(new KeyValue("辛弃疾 清平乐·村居", "sc_203.txt"));
		list.add(new KeyValue("辛弃疾 破阵子·为陈同甫赋壮词以寄之", "sc_204.txt"));
		list.add(new KeyValue("辛弃疾 丑奴儿·书博山②道中壁", "sc_205.txt"));
		list.add(new KeyValue("辛弃疾 贺新郎·别茂嘉十二弟", "sc_206.txt"));
		list.add(new KeyValue("辛弃疾 念奴娇·书东流村壁", "sc_207.txt"));
		list.add(new KeyValue("辛弃疾 汉宫春·立春", "sc_208.txt"));
		list.add(new KeyValue("辛弃疾 贺新郎·赋琵琶", "sc_209.txt"));
		list.add(new KeyValue("辛弃疾 水龙吟·登建康赏心亭", "sc_210.txt"));
		list.add(new KeyValue("辛弃疾 摸鱼儿", "sc_211.txt"));
		list.add(new KeyValue("辛弃疾 木兰花慢·滁州送范倅", "sc_212.txt"));
		list.add(new KeyValue("辛弃疾 永遇乐·京口北固亭怀古", "sc_213.txt"));
		list.add(new KeyValue("辛弃疾 祝英台令·晚春", "sc_214.txt"));
		list.add(new KeyValue("辛弃疾 青玉案·元夕", "sc_215.txt"));
		list.add(new KeyValue("辛弃疾 菩萨蛮·书江西造口壁", "sc_216.txt"));
		list.add(new KeyValue("辛弃疾 鹧鸪天·鹅湖归病起作", "sc_217.txt"));
		list.add(new KeyValue("俞国宝 风入松", "sc_218.txt"));
		list.add(new KeyValue("姜夔   霓裳中序第一", "sc_219.txt"));
		list.add(new KeyValue("姜夔   点绛唇", "sc_220.txt"));
		list.add(new KeyValue("姜夔   踏莎行", "sc_221.txt"));
		list.add(new KeyValue("姜夔   八归·湘中送胡德华", "sc_222.txt"));
		list.add(new KeyValue("姜夔   念奴娇", "sc_223.txt"));
		list.add(new KeyValue("姜夔   长亭怨慢", "sc_224.txt"));
		list.add(new KeyValue("姜夔   杏花天影", "sc_225.txt"));
		list.add(new KeyValue("姜夔   扬州慢", "sc_226.txt"));
		list.add(new KeyValue("姜夔   淡黄柳", "sc_227.txt"));
		list.add(new KeyValue("姜夔   暗香", "sc_228.txt"));
		list.add(new KeyValue("姜夔   疏影", "sc_229.txt"));
		list.add(new KeyValue("姜夔   翠楼吟", "sc_230.txt"));
		list.add(new KeyValue("姜夔   浣溪沙", "sc_231.txt"));
		list.add(new KeyValue("姜夔   浣溪沙", "sc_232.txt"));
		list.add(new KeyValue("姜夔   一萼红", "sc_233.txt"));
		list.add(new KeyValue("史达祖 绮罗香·咏春雨", "sc_234.txt"));
		list.add(new KeyValue("史达祖 双双燕·咏燕", "sc_235.txt"));
		list.add(new KeyValue("史达祖 东风第一枝·春雪", "sc_236.txt"));
		list.add(new KeyValue("史达祖 夜合花", "sc_237.txt"));
		list.add(new KeyValue("史达祖 喜迁莺", "sc_238.txt"));
		list.add(new KeyValue("史达祖 玉蝴蝶", "sc_239.txt"));
		list.add(new KeyValue("史达祖 秋霁", "sc_240.txt"));
		list.add(new KeyValue("史达祖 三姝媚", "sc_241.txt"));
		list.add(new KeyValue("史达祖 八归", "sc_242.txt"));
		list.add(new KeyValue("卢祖皋 江城子", "sc_243.txt"));
		list.add(new KeyValue("卢祖皋 宴清都", "sc_244.txt"));
		list.add(new KeyValue("严仁   木兰花", "sc_245.txt"));
		list.add(new KeyValue("刘克庄 木兰花·戏林推", "sc_246.txt"));
		list.add(new KeyValue("刘克庄 贺新郎·九日", "sc_247.txt"));
		list.add(new KeyValue("刘克庄 贺新郎·端午", "sc_248.txt"));
		list.add(new KeyValue("潘希白 大有·九日", "sc_249.txt"));
		list.add(new KeyValue("吴文英 齐天乐", "sc_250.txt"));
		list.add(new KeyValue("吴文英 夜合花", "sc_251.txt"));
		list.add(new KeyValue("吴文英 浣溪沙", "sc_252.txt"));
		list.add(new KeyValue("吴文英 齐天乐", "sc_253.txt"));
		list.add(new KeyValue("吴文英 花犯·郭希道送水仙索赋", "sc_254.txt"));
		list.add(new KeyValue("吴文英 霜叶飞·重九", "sc_255.txt"));
		list.add(new KeyValue("吴文英 宴清都·连理海棠", "sc_256.txt"));
		list.add(new KeyValue("吴文英 高阳台", "sc_257.txt"));
		list.add(new KeyValue("吴文英 祝英台近·春日客龟溪游废园", "sc_258.txt"));
		list.add(new KeyValue("吴文英 风入松", "sc_259.txt"));
		list.add(new KeyValue("吴文英 点绛唇·试灯夜初晴", "sc_260.txt"));
		list.add(new KeyValue("吴文英 八声甘州·灵岩陪庾幕诸公游", "sc_261.txt"));
		list.add(new KeyValue("吴文英 澡兰香·淮安重午", "sc_262.txt"));
		list.add(new KeyValue("吴文英 祝英台近·除夜立春", "sc_263.txt"));
		list.add(new KeyValue("吴文英 浣溪沙", "sc_264.txt"));
		list.add(new KeyValue("吴文英 望江南", "sc_265.txt"));
		list.add(new KeyValue("吴文英 惜黄花慢", "sc_266.txt"));
		list.add(new KeyValue("吴文英 高阳台·丰乐楼分韵得“如”字", "sc_267.txt"));
		list.add(new KeyValue("吴文英 三姝媚·过都城旧居有感", "sc_268.txt"));
		list.add(new KeyValue("吴文英 踏莎行", "sc_269.txt"));
		list.add(new KeyValue("吴文英 鹧鸪天·化度寺作", "sc_270.txt"));
		list.add(new KeyValue("吴文英 夜游宫", "sc_271.txt"));
		list.add(new KeyValue("吴文英 瑞鹤仙", "sc_272.txt"));
		list.add(new KeyValue("吴文英 贺新郎·陪履斋先生沧浪看梅", "sc_273.txt"));
		list.add(new KeyValue("吴文英 唐多令", "sc_274.txt"));
		list.add(new KeyValue("潘牥   南乡子·题南剑州妓馆", "sc_275.txt"));
		list.add(new KeyValue("刘辰翁 兰陵王·丙子送春", "sc_276.txt"));
		list.add(new KeyValue("刘辰翁 宝鼎现", "sc_277.txt"));
		list.add(new KeyValue("刘辰翁 永遇乐", "sc_278.txt"));
		list.add(new KeyValue("刘辰翁 摸鱼儿·酒边留同年徐云屋", "sc_279.txt"));
		list.add(new KeyValue("周密   瑶华", "sc_280.txt"));
		list.add(new KeyValue("周密   高阳台·送陈君衡被召", "sc_281.txt"));
		list.add(new KeyValue("周密   玉京秋", "sc_282.txt"));
		list.add(new KeyValue("周密   花犯·水仙花", "sc_283.txt"));
		list.add(new KeyValue("朱嗣发 摸鱼儿", "sc_284.txt"));
		list.add(new KeyValue("王沂孙 眉妩·新月", "sc_285.txt"));
		list.add(new KeyValue("王沂孙 齐天乐·蝉", "sc_286.txt"));
		list.add(new KeyValue("王沂孙 天香·龙涎香", "sc_287.txt"));
		list.add(new KeyValue("王沂孙 长亭怨慢·重过中庵故园", "sc_288.txt"));
		list.add(new KeyValue("彭元逊 解佩环·寻梅不见", "sc_289.txt"));
		list.add(new KeyValue("彭元逊 六丑·杨花", "sc_290.txt"));
		list.add(new KeyValue("僧挥   诉衷情·寒食", "sc_291.txt"));
		list.add(new KeyValue("僧挥   金明池", "sc_292.txt"));
		list.add(new KeyValue("蒋捷   虞美人·听雨", "sc_293.txt"));
		list.add(new KeyValue("蒋捷   贺新郎", "sc_294.txt"));
		list.add(new KeyValue("张炎   渡江云", "sc_295.txt"));
		list.add(new KeyValue("张炎   疏影·咏荷叶", "sc_296.txt"));
		list.add(new KeyValue("张炎   甘州", "sc_297.txt"));
		list.add(new KeyValue("张炎   高阳台·西湖春感", "sc_298.txt"));
		list.add(new KeyValue("张炎   解连环·孤雁", "sc_299.txt"));
		list.add(new KeyValue("张炎   月下笛", "sc_300.txt"));
		list.add(new KeyValue("文天祥 满江红（代王夫人作）", "sc_301.txt"));
		Menu_File_Map.put("宋词三百首", list);

		list = new ArrayList<KeyValue>();
		list.add(new KeyValue("阿里西瑛 【双调】殿前欢·懒云窝", "yq_001.txt"));
		list.add(new KeyValue("阿里西瑛 【商调】凉亭乐·叹世", "yq_002.txt"));
		list.add(new KeyValue("郑光祖 蟾宫曲·梦中作", "yq_003.txt"));
		list.add(new KeyValue("元好问 【中吕】喜春来·春宴", "yq_004.txt"));
		list.add(new KeyValue("元好问 【中吕】喜春来·春宴", "yq_005.txt"));
		list.add(new KeyValue("元好问 【仙吕】后庭花破子", "yq_006.txt"));
		list.add(new KeyValue("元好问 【双调】骤雨打新荷", "yq_007.txt"));
		list.add(new KeyValue("杨果   【越调】小桃红", "yq_008.txt"));
		list.add(new KeyValue("杨果   【越调】小桃红", "yq_009.txt"));
		list.add(new KeyValue("商政叔 【越调】天净沙", "yq_010.txt"));
		list.add(new KeyValue("刘秉忠 【南吕】干荷叶", "yq_011.txt"));
		list.add(new KeyValue("王和卿 【双调】拨不断·自叹", "yq_012.txt"));
		list.add(new KeyValue("王和卿 【仙吕】醉中天·咏大蝴蝶", "yq_013.txt"));
		list.add(new KeyValue("魏初   【黄钟】人月圆·为细君寿", "yq_014.txt"));
		list.add(new KeyValue("盍西村 【越调】小桃红·江岸水灯", "yq_015.txt"));
		list.add(new KeyValue("盍西村 【越调】小桃红·杂咏", "yq_016.txt"));
		list.add(new KeyValue("商挺   【双调】潘妃曲", "yq_017.txt"));
		list.add(new KeyValue("胡祗遹 【中吕】阳春曲·春景", "yq_018.txt"));
		list.add(new KeyValue("胡祗遹 【双调】沉醉东风", "yq_019.txt"));
		list.add(new KeyValue("王恽   【越调】平湖乐", "yq_020.txt"));
		list.add(new KeyValue("王恽   【越调】平湖乐·尧庙秋社", "yq_021.txt"));
		list.add(new KeyValue("王恽   【正宫】黑漆弩·游金山寺（序略）", "yq_022.txt"));
		list.add(new KeyValue("陈草庵 【中吕】山坡羊", "yq_023.txt"));
		list.add(new KeyValue("陈草庵 【中吕】山坡羊", "yq_024.txt"));
		list.add(new KeyValue("陈草庵 【中吕】山坡羊", "yq_025.txt"));
		list.add(new KeyValue("徐琰   【双调】沉醉东风·赠歌者吹箫", "yq_026.txt"));
		list.add(new KeyValue("姚燧   【越调】凭阑人·寄征衣", "yq_027.txt"));
		list.add(new KeyValue("姚燧   【中吕】普天乐·别友", "yq_028.txt"));
		list.add(new KeyValue("姚燧   【中吕】阳春曲", "yq_029.txt"));
		list.add(new KeyValue("姚燧   【中吕】醉高歌·感怀", "yq_030.txt"));
		list.add(new KeyValue("姚燧   【双调】寿阳曲", "yq_031.txt"));
		list.add(new KeyValue("姚燧   【双调】寿阳曲·咏李白", "yq_032.txt"));
		list.add(new KeyValue("姚燧   【越调】凭阑人", "yq_033.txt"));
		list.add(new KeyValue("姚燧   【中吕】醉高歌·感怀", "yq_034.txt"));
		list.add(new KeyValue("关汉卿 【南吕】一枝花·不伏老", "yq_035.txt"));
		list.add(new KeyValue("关汉卿 【南吕】四块玉·别情", "yq_036.txt"));
		list.add(new KeyValue("关汉卿 【商调】梧叶儿·别情", "yq_037.txt"));
		list.add(new KeyValue("关汉卿 【双调】大德歌·春", "yq_038.txt"));
		list.add(new KeyValue("关汉卿 【双调】大德歌·夏", "yq_039.txt"));
		list.add(new KeyValue("关汉卿 【双调】大德歌·秋", "yq_040.txt"));
		list.add(new KeyValue("关汉卿 【双调】沉醉东风", "yq_041.txt"));
		list.add(new KeyValue("关汉卿 【双调】碧玉箫", "yq_042.txt"));
		list.add(new KeyValue("卢挚   【双调】沉醉东风·秋景", "yq_043.txt"));
		list.add(new KeyValue("卢挚   【双调】蟾宫曲·萧娥", "yq_044.txt"));
		list.add(new KeyValue("卢挚   【双调】寿阳曲·别珠帘秀", "yq_045.txt"));
		list.add(new KeyValue("卢挚   【黄钟】节节高·题洞庭鹿角庙壁", "yq_046.txt"));
		list.add(new KeyValue("卢挚   【双调】殿前欢·酒兴", "yq_047.txt"));
		list.add(new KeyValue("卢挚   【双调】沉醉东风·闲居", "yq_048.txt"));
		list.add(new KeyValue("卢挚   【双调】沉醉东风·七夕", "yq_049.txt"));
		list.add(new KeyValue("卢挚   【双调】蟾宫曲·寒食新野道中", "yq_050.txt"));
		list.add(new KeyValue("卢挚   【双调】沉醉东风·闲居", "yq_051.txt"));
		list.add(new KeyValue("庾天锡 【双调】蟾宫曲", "yq_052.txt"));
		list.add(new KeyValue("冯子振 【正宫】鹦鹉曲·农夫渴雨", "yq_053.txt"));
		list.add(new KeyValue("真氏   【仙吕】解三酲·奴本是明珠擎掌", "yq_054.txt"));
		list.add(new KeyValue("赵孟頫 【仙吕】后庭花", "yq_055.txt"));
		list.add(new KeyValue("刘燕歌 【仙吕】太常引·饯齐参议归山东", "yq_056.txt"));
		list.add(new KeyValue("马致远 【双调】夜行船·秋思", "yq_057.txt"));
		list.add(new KeyValue("马致远 【南吕】四块玉·恬退", "yq_058.txt"));
		list.add(new KeyValue("马致远 【越调】天净沙·秋思", "yq_059.txt"));
		list.add(new KeyValue("马致远 【南吕】四块玉·紫芝路", "yq_060.txt"));
		list.add(new KeyValue("马致远 【双调】寿阳曲·远浦帆归", "yq_061.txt"));
		list.add(new KeyValue("马致远 【双调】寿阳曲", "yq_062.txt"));
		list.add(new KeyValue("马致远 【双调】寿阳曲·潇湘夜雨", "yq_063.txt"));
		list.add(new KeyValue("马致远 【双调】蟾宫曲", "yq_064.txt"));
		list.add(new KeyValue("马致远 【双调】拨不断·叹世", "yq_065.txt"));
		list.add(new KeyValue("马致远 【双调】寿阳曲·山市晴岚", "yq_066.txt"));
		list.add(new KeyValue("马致远 【双调】清江引·野兴", "yq_067.txt"));
		list.add(new KeyValue("范康   【仙吕】寄生草·酒", "yq_068.txt"));
		list.add(new KeyValue("曾瑞   【南吕】四块玉·叹世", "yq_069.txt"));
		list.add(new KeyValue("曾瑞   【南吕】骂玉郎过感皇恩采茶歌·闺情", "yq_070.txt"));
		list.add(new KeyValue("曾瑞   【南吕】四块玉·酷吏", "yq_071.txt"));
		list.add(new KeyValue("曾瑞   【中吕】山坡羊·自叹", "yq_072.txt"));
		list.add(new KeyValue("白朴   【双调】得胜乐", "yq_073.txt"));
		list.add(new KeyValue("白朴   【双调】得胜乐", "yq_074.txt"));
		list.add(new KeyValue("白朴   【双调】沉醉东风·渔夫", "yq_075.txt"));
		list.add(new KeyValue("白朴   【双调】庆东原", "yq_076.txt"));
		list.add(new KeyValue("白朴   【越调】天净沙·秋", "yq_077.txt"));
		list.add(new KeyValue("白朴   【越调】天净沙·冬", "yq_078.txt"));
		list.add(new KeyValue("邓玉宾 【正官】叨叨令·道情", "yq_079.txt"));
		list.add(new KeyValue("王伯成 【中吕】阳春曲·别情", "yq_080.txt"));
		list.add(new KeyValue("王伯成 【仙吕】春从天上来·闺怨", "yq_081.txt"));
		list.add(new KeyValue("李致远 【越调】小桃红·碧桃", "yq_082.txt"));
		list.add(new KeyValue("李致远 【双调】落梅风", "yq_083.txt"));
		list.add(new KeyValue("李致远 【双调】水仙子·春暮", "yq_084.txt"));
		list.add(new KeyValue("李致远 【双调】折桂令·读史", "yq_085.txt"));
		list.add(new KeyValue("白贲   【正宫】鹦鹉曲", "yq_086.txt"));
		list.add(new KeyValue("贯云石 【双调】寿阳曲", "yq_087.txt"));
		list.add(new KeyValue("贯云石 【双调】清江引", "yq_088.txt"));
		list.add(new KeyValue("贯云石 【中吕】红绣鞋·欢情", "yq_089.txt"));
		list.add(new KeyValue("贯云石 【双调】殿前欢", "yq_090.txt"));
		list.add(new KeyValue("贯云石 【正宫】小梁州·秋", "yq_091.txt"));
		list.add(new KeyValue("贯云石 【双调】折桂令·送春", "yq_092.txt"));
		list.add(new KeyValue("贯云石 【双调】清江引·咏梅", "yq_093.txt"));
		list.add(new KeyValue("贯云石 【双调】清江引·咏梅", "yq_094.txt"));
		list.add(new KeyValue("贯云石 【双调】清江引·惜别", "yq_095.txt"));
		list.add(new KeyValue("贯云石 【双调】清江引·立春", "yq_096.txt"));
		list.add(new KeyValue("贯云石 【正宫】塞鸿秋·代人作", "yq_097.txt"));
		list.add(new KeyValue("贯云石 【正宫】醉太平", "yq_098.txt"));
		list.add(new KeyValue("周文质 【越调】寨儿令", "yq_099.txt"));
		list.add(new KeyValue("周文质 【越调】小桃红·咏桃", "yq_100.txt"));
		list.add(new KeyValue("周文质 【双调】折桂令·过多景楼", "yq_101.txt"));
		list.add(new KeyValue("王元鼎 【正宫】醉太平·寒食", "yq_102.txt"));
		list.add(new KeyValue("王元鼎 【越调】凭阑人·闺怨", "yq_103.txt"));
		list.add(new KeyValue("王元鼎 【正宫】醉太平", "yq_104.txt"));
		list.add(new KeyValue("赵禹圭 【双调】蟾宫曲·题金山寺", "yq_105.txt"));
		list.add(new KeyValue("赵善庆 【中吕】普天乐·江头秋行", "yq_106.txt"));
		list.add(new KeyValue("赵善庆 【双调】折桂令·西湖", "yq_107.txt"));
		list.add(new KeyValue("赵善庆 【中吕】山坡羊·长安怀古", "yq_108.txt"));
		list.add(new KeyValue("赵善庆 【双调】水仙子·仲春湖上", "yq_109.txt"));
		list.add(new KeyValue("张养浩 【中吕】山坡羊·潼关怀古", "yq_110.txt"));
		list.add(new KeyValue("张养浩 【双调】庆宣和", "yq_111.txt"));
		list.add(new KeyValue("张养浩 【双调】庆东原", "yq_112.txt"));
		list.add(new KeyValue("张养浩 【双调】水仙子", "yq_113.txt"));
		list.add(new KeyValue("张养浩 【双调】雁儿落兼得胜令", "yq_114.txt"));
		list.add(new KeyValue("张养浩 【南吕】西番经", "yq_115.txt"));
		list.add(new KeyValue("张养浩 【中吕】普天乐", "yq_116.txt"));
		list.add(new KeyValue("张养浩 【中吕】山坡羊", "yq_117.txt"));
		list.add(new KeyValue("张养浩 【中吕】山坡羊", "yq_118.txt"));
		list.add(new KeyValue("张养浩 【中吕】红绣鞋", "yq_119.txt"));
		list.add(new KeyValue("张养浩 【双调】殿前欢·对菊自叹", "yq_120.txt"));
		list.add(new KeyValue("张养浩 【双调】殿前欢·登会波楼", "yq_121.txt"));
		list.add(new KeyValue("张养浩 【双调】殿前欢·玉香球花", "yq_122.txt"));
		list.add(new KeyValue("张养浩 【双调】殿前欢·村居", "yq_123.txt"));
		list.add(new KeyValue("张养浩 【中吕】朝天曲", "yq_124.txt"));
		list.add(new KeyValue("张养浩 【双调】沽美酒兼太平令", "yq_125.txt"));
		list.add(new KeyValue("张养浩 【中吕】普天乐·平沙落雁", "yq_126.txt"));
		list.add(new KeyValue("张养浩 【双调】折桂令·芦沟晓月", "yq_127.txt"));
		list.add(new KeyValue("张养浩 【中吕】普天乐·渔村落照", "yq_128.txt"));
		list.add(new KeyValue("张养浩 【双调】折桂令·诸葛武侯", "yq_129.txt"));
		list.add(new KeyValue("张养浩 【双调】折桂令·李翰林", "yq_130.txt"));
		list.add(new KeyValue("邓玉宾子 【双调】雁儿落过得胜令·闲适", "yq_131.txt"));
		list.add(new KeyValue("邓玉宾子 【双调】雁儿落过得胜令·闲适", "yq_132.txt"));
		list.add(new KeyValue("卫立中 【双调】殿前欢", "yq_133.txt"));
		list.add(new KeyValue("吴西逸 【双调】雁儿落过得胜令", "yq_134.txt"));
		list.add(new KeyValue("吴西逸 【双调】蟾宫曲·山间书事", "yq_135.txt"));
		list.add(new KeyValue("吴西逸 【越调】天净沙·闲题", "yq_136.txt"));
		list.add(new KeyValue("吴西逸 【越调】天净沙·闲题", "yq_137.txt"));
		list.add(new KeyValue("吴西逸 【双调】蟾宫曲·寄友", "yq_138.txt"));
		list.add(new KeyValue("高克礼 【越调】黄蔷薇过庆元贞", "yq_139.txt"));
		list.add(new KeyValue("高克礼 【双调】雁儿落过得胜令", "yq_140.txt"));
		list.add(new KeyValue("乔吉   【越调】小桃红·孙氏壁间画竹", "yq_141.txt"));
		list.add(new KeyValue("乔吉   【中吕】山坡羊·寓兴", "yq_142.txt"));
		list.add(new KeyValue("乔吉   【正宫】绿玄遍·自述", "yq_143.txt"));
		list.add(new KeyValue("乔吉   【中吕】山坡羊·冬日写怀", "yq_144.txt"));
		list.add(new KeyValue("乔吉   【南吕】玉交枝·失题", "yq_145.txt"));
		list.add(new KeyValue("乔吉   【中吕】山坡羊·自警", "yq_146.txt"));
		list.add(new KeyValue("乔吉   【越调】凭阑人·金陵道中", "yq_147.txt"));
		list.add(new KeyValue("乔吉   【中吕】山坡羊·失题", "yq_148.txt"));
		list.add(new KeyValue("乔吉   【越调】小桃红·立春遣兴", "yq_149.txt"));
		list.add(new KeyValue("乔吉   【中吕】满庭芳·渔父词", "yq_150.txt"));
		list.add(new KeyValue("乔吉   【中吕】满庭芳·渔父词", "yq_151.txt"));
		list.add(new KeyValue("乔吉   【双调】卖花声·悟世", "yq_152.txt"));
		list.add(new KeyValue("乔吉   【越调】小桃红·孙氏壁间画竹", "yq_153.txt"));
		list.add(new KeyValue("乔吉   【双调】水仙子·咏雪", "yq_154.txt"));
		list.add(new KeyValue("乔吉   【双调】折桂令·自述", "yq_155.txt"));
		list.add(new KeyValue("乔吉   【双调】水仙子·梦觉", "yq_156.txt"));
		list.add(new KeyValue("乔吉   【双调】水仙子·寻梅", "yq_157.txt"));
		list.add(new KeyValue("乔吉   【双调】清江引·即景", "yq_158.txt"));
		list.add(new KeyValue("乔吉   【双调】折桂令·客窗清明", "yq_159.txt"));
		list.add(new KeyValue("乔吉   【双调】水仙子·重观瀑布", "yq_160.txt"));
		list.add(new KeyValue("乔吉   【越调】天净沙·即事", "yq_161.txt"));
		list.add(new KeyValue("乔吉   【双调】春闺怨", "yq_162.txt"));
		list.add(new KeyValue("乔吉   【双调】雁儿落过得胜令·忆别", "yq_163.txt"));
		list.add(new KeyValue("乔吉   【双调】折桂令·荆溪即事", "yq_164.txt"));
		list.add(new KeyValue("乔吉   【双调】水仙子·赠江云", "yq_165.txt"));
		list.add(new KeyValue("刘致   【中吕】朝天子·邸万户席上", "yq_166.txt"));
		list.add(new KeyValue("刘致   【双调】清江引", "yq_167.txt"));
		list.add(new KeyValue("刘致   【双调】殿前欢", "yq_168.txt"));
		list.add(new KeyValue("薛昂夫 【中吕】朝天曲", "yq_169.txt"));
		list.add(new KeyValue("薛昂夫 【双调】蟾宫曲·雪", "yq_170.txt"));
		list.add(new KeyValue("薛昂夫 【正宫】塞鸿秋", "yq_171.txt"));
		list.add(new KeyValue("薛昂夫 【双调】庆东原·西皋亭适应", "yq_172.txt"));
		list.add(new KeyValue("薛昂夫 【中吕】山坡羊·西湖杂咏·秋", "yq_173.txt"));
		list.add(new KeyValue("薛昂夫 【中吕】山坡羊·述怀", "yq_174.txt"));
		list.add(new KeyValue("薛昂夫 【双调】楚天遥过清江引", "yq_175.txt"));
		list.add(new KeyValue("薛昂夫 【双调】蟾宫曲·题烂柯石桥", "yq_176.txt"));
		list.add(new KeyValue("薛昂夫 【中吕】朝天曲", "yq_177.txt"));
		list.add(new KeyValue("张雨   【双调】水仙子", "yq_178.txt"));
		list.add(new KeyValue("吴弘道 【中吕】上小楼·钱塘感旧", "yq_179.txt"));
		list.add(new KeyValue("阿鲁威 【双调】蟾宫曲", "yq_180.txt"));
		list.add(new KeyValue("阿鲁威 【双调】湘妃怨", "yq_181.txt"));
		list.add(new KeyValue("虞集   【双调】折桂令", "yq_182.txt"));
		list.add(new KeyValue("马谦斋 【越调】柳营曲·叹世", "yq_183.txt"));
		list.add(new KeyValue("马谦斋 【双调】水仙子·咏竹", "yq_184.txt"));
		list.add(new KeyValue("马谦斋 【双调】沉醉东风·自悟", "yq_185.txt"));
		list.add(new KeyValue("马谦斋 【双调】水仙子·雪夜", "yq_186.txt"));
		list.add(new KeyValue("张可久 【中吕】满庭芳·金华道中", "yq_187.txt"));
		list.add(new KeyValue("张可久 【黄钟】人月圆·会稽怀古", "yq_188.txt"));
		list.add(new KeyValue("张可久 【南吕】四块玉·乐闲", "yq_189.txt"));
		list.add(new KeyValue("张可久 【南吕】金字经·雪夜", "yq_190.txt"));
		list.add(new KeyValue("张可久 【黄钟】人月圆·山中书事", "yq_191.txt"));
		list.add(new KeyValue("张可久 【商调】梧叶儿·湖山夜景", "yq_192.txt"));
		list.add(new KeyValue("张可久 【南吕】金字经·乐闲", "yq_193.txt"));
		list.add(new KeyValue("张可久 【商调】梧叶儿·春日郊行", "yq_194.txt"));
		list.add(new KeyValue("张可久 【中吕】卖花声·怀古", "yq_195.txt"));
		list.add(new KeyValue("张可久 【双调】庆东原·次马致远先辈韵九篇", "yq_196.txt"));
		list.add(new KeyValue("张可久 【越调】天净沙·江上", "yq_197.txt"));
		list.add(new KeyValue("张可久 【黄钟】人月圆·开吴淞江遇雪", "yq_198.txt"));
		list.add(new KeyValue("张可久 【中吕】普天乐·暮春即事", "yq_199.txt"));
		list.add(new KeyValue("张可久 【双调】折桂令·九日", "yq_200.txt"));
		list.add(new KeyValue("张可久 【双调】折桂令·读史有感", "yq_201.txt"));
		list.add(new KeyValue("张可久 【中吕】满庭芳·春思", "yq_202.txt"));
		list.add(new KeyValue("张可久 【双调】水仙子·归兴", "yq_203.txt"));
		list.add(new KeyValue("张可久 【商调】梧叶儿·有所思", "yq_204.txt"));
		list.add(new KeyValue("张可久 【双调】殿前欢·春晚", "yq_205.txt"));
		list.add(new KeyValue("张可久 【双调】殿前欢·客中", "yq_206.txt"));
		list.add(new KeyValue("张可久 【双调】折桂令·西陵送别", "yq_207.txt"));
		list.add(new KeyValue("张可久 【越调】天净沙·晚步", "yq_208.txt"));
		list.add(new KeyValue("张可久 【双调】清江引·采石江上", "yq_209.txt"));
		list.add(new KeyValue("张可久 【中吕】红绣鞋·秋望", "yq_210.txt"));
		list.add(new KeyValue("张可久 【双调】湘妃怨·次韵金陵怀古", "yq_211.txt"));
		list.add(new KeyValue("张可久 【双调】落梅风·春晚", "yq_212.txt"));
		list.add(new KeyValue("徐再思 【中吕】红绣鞋·雪", "yq_213.txt"));
		list.add(new KeyValue("徐再思 【黄钟】红锦袍", "yq_214.txt"));
		list.add(new KeyValue("徐再思 【黄钟】人月圆·兰亭", "yq_215.txt"));
		list.add(new KeyValue("徐再思 【双调】水仙子·夜雨", "yq_216.txt"));
		list.add(new KeyValue("徐再思 【越调】天净沙·秋江夜泊", "yq_217.txt"));
		list.add(new KeyValue("徐再思 【双调】沉醉东风·春情", "yq_218.txt"));
		list.add(new KeyValue("徐再思 【商调】梧叶儿·革步", "yq_219.txt"));
		list.add(new KeyValue("徐再思 【中吕】阳春曲·皇亭晚泊", "yq_220.txt"));
		list.add(new KeyValue("徐再思 【中吕】普天乐·西山夕照", "yq_221.txt"));
		list.add(new KeyValue("徐再思 【双调】蟾宫曲·春情", "yq_222.txt"));
		list.add(new KeyValue("徐再思 【双调】水仙子", "yq_223.txt"));
		list.add(new KeyValue("钱霖   【双调】清江引", "yq_224.txt"));
		list.add(new KeyValue("孙周卿 【双调】水仙子·舟中", "yq_225.txt"));
		list.add(new KeyValue("孙周卿 【双调】水仙子·山居自乐", "yq_226.txt"));
		list.add(new KeyValue("孙周卿 【双调】蟾宫曲·自乐", "yq_227.txt"));
		list.add(new KeyValue("孙周卿 【双调】沉醉东风·宫词", "yq_228.txt"));
		list.add(new KeyValue("吕济民 【双调】蟾宫曲·赠楚云", "yq_229.txt"));
		list.add(new KeyValue("曹德   【双调】折桂令·江头即事", "yq_230.txt"));
		list.add(new KeyValue("曹德   【双调】折桂令·西湖早春", "yq_231.txt"));
		list.add(new KeyValue("曹德   【双调】庆东原·江头即事", "yq_232.txt"));
		list.add(new KeyValue("杨朝英 【双调】水仙子·自足", "yq_233.txt"));
		list.add(new KeyValue("杨朝英 【商调】梧叶儿·客中闻雨", "yq_234.txt"));
		list.add(new KeyValue("杨朝英 【中吕】阳春曲", "yq_235.txt"));
		list.add(new KeyValue("杨朝英 【双调】清江引", "yq_236.txt"));
		list.add(new KeyValue("钟嗣成 【正宫】醉太平", "yq_237.txt"));
		list.add(new KeyValue("钟嗣成 【双调】凌波仙·吊乔梦符", "yq_238.txt"));
		list.add(new KeyValue("钟嗣成 【双调】水仙子·吊宫大用", "yq_239.txt"));
		list.add(new KeyValue("钟嗣成 【正宫】醉太平", "yq_240.txt"));
		list.add(new KeyValue("钟嗣成 【双调】水仙子·吊施君美", "yq_241.txt"));
		list.add(new KeyValue("李齐贤 【黄钟】人月圆·马嵬效吴彦高", "yq_242.txt"));
		list.add(new KeyValue("赵显宏 【中吕】满庭芳·渔", "yq_243.txt"));
		list.add(new KeyValue("赵显宏 【中吕】满庭芳·牧", "yq_244.txt"));
		list.add(new KeyValue("赵显宏 【双调】清江引", "yq_245.txt"));
		list.add(new KeyValue("赵显宏 【双调】清江引·情", "yq_246.txt"));
		list.add(new KeyValue("周德清 【正宫】塞鸿秋·浔阳即景", "yq_247.txt"));
		list.add(new KeyValue("周德清 【中吕】满庭芳·误国贼秦桧", "yq_248.txt"));
		list.add(new KeyValue("周德清 【中吕】满庭芳·看岳王传", "yq_249.txt"));
		list.add(new KeyValue("周德清 【中吕】朝天子·秋夜客怀", "yq_250.txt"));
		list.add(new KeyValue("周德清 【双调】蟾宫曲·别友", "yq_251.txt"));
		list.add(new KeyValue("周德清 【双调】蟾宫曲", "yq_252.txt"));
		list.add(new KeyValue("周德清 【中吕】红绣鞋·郊行", "yq_253.txt"));
		list.add(new KeyValue("周德清 【中吕】红绣鞋·郊行", "yq_254.txt"));
		list.add(new KeyValue("周德清 【双调】蟾宫曲·别友", "yq_255.txt"));
		list.add(new KeyValue("倪瓒   【越调】小桃红", "yq_256.txt"));
		list.add(new KeyValue("倪瓒   【黄钟】人月圆", "yq_257.txt"));
		list.add(new KeyValue("倪瓒   【越调】凭阑人·赠吴国良", "yq_258.txt"));
		list.add(new KeyValue("吕止庵 【仙吕】后庭花·秋思", "yq_259.txt"));
		list.add(new KeyValue("吕止庵 【仙吕】后庭花·冷泉亭", "yq_260.txt"));
		list.add(new KeyValue("宋方壶 【双调】清江引·托咏", "yq_261.txt"));
		list.add(new KeyValue("宋方壶 【中吕】山坡羊·道情", "yq_262.txt"));
		list.add(new KeyValue("宋方壶 【中吕】一半儿", "yq_263.txt"));
		list.add(new KeyValue("宋方壶 【双调】水仙子·叹世", "yq_264.txt"));
		list.add(new KeyValue("宋方壶 【双调】水仙子·隐者", "yq_265.txt"));
		list.add(new KeyValue("王举之 【中吕】红绣鞋·秋日湖上", "yq_266.txt"));
		list.add(new KeyValue("王举之 【双调】折桂令·怀钱塘", "yq_267.txt"));
		list.add(new KeyValue("王举之 【中吕】红绣鞋·栖云吊贯酸斋", "yq_268.txt"));
		list.add(new KeyValue("王举之 【双调】折桂令·虎顶杯", "yq_269.txt"));
		list.add(new KeyValue("王举之 【双调】折桂令·读史有感", "yq_270.txt"));
		list.add(new KeyValue("王爱山 【中吕】上小楼·自适", "yq_271.txt"));
		list.add(new KeyValue("李爱山 【南吕】四块玉·美色", "yq_272.txt"));
		list.add(new KeyValue("李爱山 【双调】寿阳曲·厌纷", "yq_273.txt"));
		list.add(new KeyValue("刘庭信 【双调】折桂令·忆别", "yq_274.txt"));
		list.add(new KeyValue("刘庭信 【双调】折桂令·题情", "yq_275.txt"));
		list.add(new KeyValue("刘庭信 【双调】水仙子·相思", "yq_276.txt"));
		list.add(new KeyValue("汪元亨 【正宫】醉太平·警世", "yq_277.txt"));
		list.add(new KeyValue("汪元亨 【双调】雁儿落过得胜令·归隐", "yq_278.txt"));
		list.add(new KeyValue("李邦祐 【双调】转调淘金令·思情", "yq_279.txt"));
		list.add(new KeyValue("舒頔   【双调】折桂令·寿张德中时三月三日", "yq_280.txt"));
		list.add(new KeyValue("查德卿 【越调】柳营曲·江上", "yq_281.txt"));
		list.add(new KeyValue("汤式   【越调】寨儿令·听筝", "yq_282.txt"));
		list.add(new KeyValue("汤式   【正宫】小梁州·九日渡江", "yq_283.txt"));
		list.add(new KeyValue("汤式   【双调】天香引·留别友人", "yq_284.txt"));
		list.add(new KeyValue("汤式   【越调】天净沙·闲居杂兴", "yq_285.txt"));
		list.add(new KeyValue("汤式   【越调】柳营曲·春思", "yq_286.txt"));
		list.add(new KeyValue("无名氏 【南吕】干荷叶", "yq_287.txt"));
		list.add(new KeyValue("无名氏 【正宫】叨叨令", "yq_288.txt"));
		list.add(new KeyValue("无名氏 【中吕】喜春来", "yq_289.txt"));
		list.add(new KeyValue("无名氏 【正宫】塞鸿秋", "yq_290.txt"));
		list.add(new KeyValue("无名氏 【正宫】醉太平·叹子弟", "yq_291.txt"));
		list.add(new KeyValue("无名氏 【仙吕】寄生草", "yq_292.txt"));
		list.add(new KeyValue("无名氏 【大石调】初生月儿", "yq_293.txt"));
		list.add(new KeyValue("无名氏 【越调】天净沙", "yq_294.txt"));
		list.add(new KeyValue("无名氏 【正宫】塞鸿秋·山行警", "yq_295.txt"));
		list.add(new KeyValue("无名氏 【正宫】醉太平·讥贪小利者", "yq_296.txt"));
		list.add(new KeyValue("无名氏 【中吕】喜春来", "yq_297.txt"));
		list.add(new KeyValue("无名氏 【中吕】喜春来·四节", "yq_298.txt"));
		list.add(new KeyValue("珠帘秀 【双调】寿阳曲·答卢疏斋", "yq_299.txt"));
		list.add(new KeyValue("奥敦周卿 【双调】蟾宫曲·西湖", "yq_300.txt"));
		list.add(new KeyValue("奥敦周卿 【双调】蟾宫曲·西湖", "yq_301.txt"));
		Menu_File_Map.put("元曲三百首", list);

		list = new ArrayList<KeyValue>();
		list.add(new KeyValue("王维   渭城曲", "ts_304.txt"));
		list.add(new KeyValue("王维   秋夜曲", "ts_305.txt"));
		list.add(new KeyValue("王昌龄 长信怨", "ts_306.txt"));
		list.add(new KeyValue("王昌龄 出塞", "ts_307.txt"));
		list.add(new KeyValue("李白   清平调·其一", "ts_308.txt"));
		list.add(new KeyValue("李白   清平调·其二", "ts_309.txt"));
		list.add(new KeyValue("李白   清平调·其三", "ts_310.txt"));
		list.add(new KeyValue("王之涣 出塞", "ts_311.txt"));
		list.add(new KeyValue("杜秋娘 金缕衣", "ts_312.txt"));
		// 后加的
		list.add(new KeyValue("沈全期 古意呈补阙乔知之", "ts_215.txt"));
		// 后加的
		list.add(new KeyValue("李颀   古从军行", "ts_069.txt"));
		list.add(new KeyValue("王维   洛阳女儿行", "ts_070.txt"));
		list.add(new KeyValue("王维   老将行", "ts_071.txt"));
		list.add(new KeyValue("王维   桃源行", "ts_072.txt"));
		list.add(new KeyValue("李白   蜀道难", "ts_073.txt"));
		list.add(new KeyValue("李白   长相思·其一", "ts_074.txt"));
		list.add(new KeyValue("李白   长相思·其二", "ts_075.txt"));
		list.add(new KeyValue("李白   行路难", "ts_076.txt"));
		list.add(new KeyValue("李白   将进酒", "ts_077.txt"));
		list.add(new KeyValue("杜甫   兵车行", "ts_078.txt"));
		list.add(new KeyValue("杜甫   丽人行", "ts_079.txt"));
		list.add(new KeyValue("杜甫   哀江头", "ts_080.txt"));
		list.add(new KeyValue("杜甫   哀王孙", "ts_081.txt"));
		Menu_File_Map.put("七言乐府", list);

		list = new ArrayList<KeyValue>();
		list.add(new KeyValue("贺知章 回乡偶书", "ts_253.txt"));
		list.add(new KeyValue("张旭   桃花溪", "ts_254.txt"));
		list.add(new KeyValue("王维   九月九日忆山东兄弟", "ts_255.txt"));
		list.add(new KeyValue("王昌龄 芙蓉楼送辛渐", "ts_256.txt"));
		list.add(new KeyValue("王昌龄 闺怨", "ts_257.txt"));
		list.add(new KeyValue("王昌龄 春宫曲", "ts_258.txt"));
		list.add(new KeyValue("王翰   凉州词", "ts_259.txt"));
		list.add(new KeyValue("李白   送孟浩然之广陵", "ts_260.txt"));
		list.add(new KeyValue("李白   早发白帝城", "ts_261.txt"));
		list.add(new KeyValue("岑参   逢入京使", "ts_262.txt"));
		list.add(new KeyValue("杜甫   江南逢李龟年", "ts_263.txt"));
		list.add(new KeyValue("韦应物 滁州西涧", "ts_264.txt"));
		list.add(new KeyValue("张继   枫桥夜泊", "ts_265.txt"));
		list.add(new KeyValue("韩翎   寒食", "ts_266.txt"));
		list.add(new KeyValue("刘方平 月夜", "ts_267.txt"));
		list.add(new KeyValue("刘方平 春怨", "ts_268.txt"));
		list.add(new KeyValue("柳中庸 征人怨", "ts_269.txt"));
		list.add(new KeyValue("顾况   宫词", "ts_270.txt"));
		list.add(new KeyValue("李益   夜上受降城闻笛", "ts_271.txt"));
		list.add(new KeyValue("刘禹锡 乌衣巷", "ts_272.txt"));
		list.add(new KeyValue("刘禹锡 春词", "ts_273.txt"));
		list.add(new KeyValue("白居易 后宫词", "ts_274.txt"));
		list.add(new KeyValue("张祜   赠内人", "ts_275.txt"));
		list.add(new KeyValue("张祜   集灵台·其一", "ts_276.txt"));
		list.add(new KeyValue("张祜   集灵台·其二", "ts_277.txt"));
		list.add(new KeyValue("张祜   题金陵渡", "ts_278.txt"));
		list.add(new KeyValue("朱庆余 宫词", "ts_279.txt"));
		list.add(new KeyValue("朱庆余 近试上张水部", "ts_280.txt"));
		list.add(new KeyValue("杜牧   将赴吴兴登乐游原", "ts_281.txt"));
		list.add(new KeyValue("杜牧   赤壁", "ts_282.txt"));
		list.add(new KeyValue("杜牧   泊秦淮", "ts_283.txt"));
		list.add(new KeyValue("杜牧   寄扬州韩绰判官", "ts_284.txt"));
		list.add(new KeyValue("杜牧   遣怀", "ts_285.txt"));
		list.add(new KeyValue("杜牧   秋夕", "ts_286.txt"));
		list.add(new KeyValue("杜牧   赠别·其一", "ts_287.txt"));
		list.add(new KeyValue("杜牧   赠别·其二", "ts_288.txt"));
		list.add(new KeyValue("杜牧   金谷园", "ts_289.txt"));
		list.add(new KeyValue("李商隐 夜雨寄北", "ts_290.txt"));
		list.add(new KeyValue("李商隐 寄令狐郎中", "ts_291.txt"));
		list.add(new KeyValue("李商隐 为有", "ts_292.txt"));
		list.add(new KeyValue("李商隐 隋宫", "ts_293.txt"));
		list.add(new KeyValue("李商隐 瑶池", "ts_294.txt"));
		list.add(new KeyValue("李商隐 嫦娥", "ts_295.txt"));
		list.add(new KeyValue("李商隐 贾生", "ts_296.txt"));
		list.add(new KeyValue("温庭筠 瑶瑟怨", "ts_297.txt"));
		list.add(new KeyValue("郑畋   马嵬坡", "ts_298.txt"));
		list.add(new KeyValue("韩翎   已凉", "ts_299.txt"));
		list.add(new KeyValue("韦庄   金陵图", "ts_300.txt"));
		list.add(new KeyValue("陈陶   陇西行", "ts_301.txt"));
		list.add(new KeyValue("张泌   寄人", "ts_302.txt"));
		list.add(new KeyValue("无名氏 杂诗", "ts_303.txt"));
		Menu_File_Map.put("七言绝句", list);

		list = new ArrayList<KeyValue>();
		list.add(new KeyValue("崔颢   长干行·其一", "ts_245.txt"));
		list.add(new KeyValue("崔颢   长干行·其二", "ts_246.txt"));
		list.add(new KeyValue("李白   玉阶怨", "ts_247.txt"));
		list.add(new KeyValue("卢纶   塞下曲·其一", "ts_248.txt"));
		list.add(new KeyValue("卢纶   塞下曲·其二", "ts_249.txt"));
		list.add(new KeyValue("卢纶   塞下曲·其三", "ts_250.txt"));
		list.add(new KeyValue("卢纶   塞下曲·其四", "ts_251.txt"));
		list.add(new KeyValue("李益   江南曲", "ts_252.txt"));
		// 后加的
		list.add(new KeyValue("王昌龄 塞下曲·其一", "ts_033.txt"));
		list.add(new KeyValue("王昌龄 塞下曲·其二", "ts_034.txt"));
		list.add(new KeyValue("李白   关山月", "ts_035.txt"));
		list.add(new KeyValue("李白   子夜秋歌", "ts_036.txt"));
		list.add(new KeyValue("李白   长干行", "ts_037.txt"));
		list.add(new KeyValue("孟郊   列女操", "ts_038.txt"));
		list.add(new KeyValue("孟郊   游子吟", "ts_039.txt"));
		Menu_File_Map.put("五言乐府", list);

		list = new ArrayList<KeyValue>();
		list.add(new KeyValue("王维   鹿柴", "ts_216.txt"));
		list.add(new KeyValue("王维   竹里馆", "ts_217.txt"));
		list.add(new KeyValue("王维   送别", "ts_218.txt"));
		list.add(new KeyValue("王维   相思", "ts_219.txt"));
		list.add(new KeyValue("王维   杂诗", "ts_220.txt"));
		list.add(new KeyValue("裴迪   送崔九", "ts_221.txt"));
		list.add(new KeyValue("祖咏   终南望余雪", "ts_222.txt"));
		list.add(new KeyValue("孟浩然 宿建德江", "ts_223.txt"));
		list.add(new KeyValue("孟浩然 春晓", "ts_224.txt"));
		list.add(new KeyValue("李白   夜思", "ts_225.txt"));
		list.add(new KeyValue("李白   怨情", "ts_226.txt"));
		list.add(new KeyValue("杜甫   八阵图", "ts_227.txt"));
		list.add(new KeyValue("王之涣 登鹳雀楼", "ts_228.txt"));
		list.add(new KeyValue("刘长卿 送灵澈", "ts_229.txt"));
		list.add(new KeyValue("刘长卿 弹琴", "ts_230.txt"));
		list.add(new KeyValue("刘长卿 送上人", "ts_231.txt"));
		list.add(new KeyValue("韦应物 秋夜寄邱员外", "ts_232.txt"));
		list.add(new KeyValue("李端   听筝", "ts_233.txt"));
		list.add(new KeyValue("王建   新嫁娘", "ts_234.txt"));
		list.add(new KeyValue("权德舆 玉台体", "ts_235.txt"));
		list.add(new KeyValue("柳宗元 江雪", "ts_236.txt"));
		list.add(new KeyValue("元稹   行宫", "ts_237.txt"));
		list.add(new KeyValue("白居易 问刘十九", "ts_238.txt"));
		list.add(new KeyValue("张祜   何满子", "ts_239.txt"));
		list.add(new KeyValue("李商隐 登乐游原", "ts_240.txt"));
		list.add(new KeyValue("贾岛   寻隐者不遇", "ts_241.txt"));
		list.add(new KeyValue("李频   渡汉江", "ts_242.txt"));
		list.add(new KeyValue("金昌绪 春怨", "ts_243.txt"));
		list.add(new KeyValue("西鄙人 哥舒歌", "ts_244.txt"));
		Menu_File_Map.put("五言绝句", list);

		list = new ArrayList<KeyValue>();
		list.add(new KeyValue("崔颢   黄鹤楼", "ts_162.txt"));
		list.add(new KeyValue("崔颢   行经华阴", "ts_163.txt"));
		list.add(new KeyValue("祖咏   望蓟门", "ts_164.txt"));
		list.add(new KeyValue("崔曙   九月登望仙台呈刘明府容", "ts_165.txt"));
		list.add(new KeyValue("李颀   送魏万之京", "ts_166.txt"));
		list.add(new KeyValue("李白   登金陵凤凰台", "ts_167.txt"));
		list.add(new KeyValue("高适   送李少府贬峡中王少府贬长沙", "ts_168.txt"));
		list.add(new KeyValue("岑参   奉和中书舍人贾至早朝大明宫", "ts_169.txt"));
		list.add(new KeyValue("王维   和贾至舍人早朝大明宫之作", "ts_170.txt"));
		list.add(new KeyValue("王维   奉和圣制从蓬莱向兴庆阁道中留春雨中春望之作应制", "ts_171.txt"));
		list.add(new KeyValue("王维   积雨辋川庄作", "ts_172.txt"));
		list.add(new KeyValue("王维   赠郭给事", "ts_173.txt"));
		list.add(new KeyValue("杜甫   蜀相", "ts_174.txt"));
		list.add(new KeyValue("杜甫   客至", "ts_175.txt"));
		list.add(new KeyValue("杜甫   野望", "ts_176.txt"));
		list.add(new KeyValue("杜甫   闻官军收河南河北", "ts_177.txt"));
		list.add(new KeyValue("杜甫   登高", "ts_178.txt"));
		list.add(new KeyValue("杜甫   登楼", "ts_179.txt"));
		list.add(new KeyValue("杜甫   宿府", "ts_180.txt"));
		list.add(new KeyValue("杜甫   阁夜", "ts_181.txt"));
		list.add(new KeyValue("杜甫   咏怀古迹·其一", "ts_182.txt"));
		list.add(new KeyValue("杜甫   咏怀古迹·其二", "ts_183.txt"));
		list.add(new KeyValue("杜甫   咏怀古迹·其三", "ts_184.txt"));
		list.add(new KeyValue("杜甫   咏怀古迹·其四", "ts_185.txt"));
		list.add(new KeyValue("杜甫   咏怀古迹·其五", "ts_186.txt"));
		list.add(new KeyValue("刘长卿 江州重别薛六柳八二员外", "ts_187.txt"));
		list.add(new KeyValue("刘长卿 长沙过贾谊宅", "ts_188.txt"));
		list.add(new KeyValue("刘长卿 自夏口至鹦鹉洲夕望岳阳寄源中丞", "ts_189.txt"));
		list.add(new KeyValue("钱起   赠阙下裴舍人", "ts_190.txt"));
		list.add(new KeyValue("韦应物 寄李儋元锡", "ts_191.txt"));
		list.add(new KeyValue("韩翃   同题仙游观", "ts_192.txt"));
		list.add(new KeyValue("皇甫冉 春思", "ts_193.txt"));
		list.add(new KeyValue("卢纶   晚次鄂州", "ts_194.txt"));
		list.add(new KeyValue("柳宗元 登柳州城楼寄漳汀封连四州刺史", "ts_195.txt"));
		list.add(new KeyValue("刘禹锡 西塞山怀古", "ts_196.txt"));
		list.add(new KeyValue("元稹   遣悲怀·其一", "ts_197.txt"));
		list.add(new KeyValue("元稹   遣悲怀·其二", "ts_198.txt"));
		list.add(new KeyValue("元稹   遣悲怀·其三", "ts_199.txt"));
		list.add(new KeyValue(
				"白居易 自河南经乱,关内阻饥,兄弟离散,各在一处.因望月有感,聊书所怀,寄上浮梁大兄,于潜七兄,乌江十五兄,兼示符离及下邽弟妹",
				"ts_200.txt"));
		list.add(new KeyValue("李商隐 锦瑟", "ts_201.txt"));
		list.add(new KeyValue("李商隐 无题", "ts_202.txt"));
		list.add(new KeyValue("李商隐 隋宫", "ts_203.txt"));
		list.add(new KeyValue("李商隐 无题·其一", "ts_204.txt"));
		list.add(new KeyValue("李商隐 无题·其二", "ts_205.txt"));
		list.add(new KeyValue("李商隐 筹笔驿", "ts_206.txt"));
		list.add(new KeyValue("李商隐 无题", "ts_207.txt"));
		list.add(new KeyValue("李商隐 春雨", "ts_208.txt"));
		list.add(new KeyValue("李商隐 无题·其一", "ts_209.txt"));
		list.add(new KeyValue("李商隐 无题·其二", "ts_210.txt"));
		list.add(new KeyValue("温庭筠 利州南渡", "ts_211.txt"));
		list.add(new KeyValue("温庭筠 苏武庙", "ts_212.txt"));
		list.add(new KeyValue("薛逢   宫词", "ts_213.txt"));
		list.add(new KeyValue("秦韬玉 贫女", "ts_214.txt"));
		Menu_File_Map.put("七言律诗", list);

		list = new ArrayList<KeyValue>();
		list.add(new KeyValue("唐玄宗 经邹鲁祭孔子而叹之", "ts_082.txt"));
		list.add(new KeyValue("张九龄 望月怀远", "ts_083.txt"));
		list.add(new KeyValue("王勃   送杜少府之任蜀州", "ts_084.txt"));
		list.add(new KeyValue("骆宾王 在狱咏蝉·并序", "ts_085.txt"));
		list.add(new KeyValue("杜审言 和晋陵陆丞相早春游望", "ts_086.txt"));
		list.add(new KeyValue("沈期   杂诗", "ts_087.txt"));
		list.add(new KeyValue("宋之问 题大庾岭北驿", "ts_088.txt"));
		list.add(new KeyValue("王湾   次北固山下", "ts_089.txt"));
		list.add(new KeyValue("常建   破山寺后禅院", "ts_090.txt"));
		list.add(new KeyValue("岑参   寄左省杜拾遗", "ts_091.txt"));
		list.add(new KeyValue("李白   赠孟浩然", "ts_092.txt"));
		list.add(new KeyValue("李白   渡荆门送别", "ts_093.txt"));
		list.add(new KeyValue("李白   送友人", "ts_094.txt"));
		list.add(new KeyValue("李白   听蜀僧浚弹琴", "ts_095.txt"));
		list.add(new KeyValue("李白   夜泊牛渚怀古", "ts_096.txt"));
		list.add(new KeyValue("杜甫   春望", "ts_097.txt"));
		list.add(new KeyValue("杜甫   月夜", "ts_098.txt"));
		list.add(new KeyValue("杜甫   春宿左省", "ts_099.txt"));
		list.add(new KeyValue(
				"杜甫   至德二载,甫自京金光门出,间道归凤翔,乾元初从左拾遗移华州掾,与亲故别,因出此门,有悲往事",
				"ts_100.txt"));
		list.add(new KeyValue("杜甫   月夜忆舍弟", "ts_101.txt"));
		list.add(new KeyValue("杜甫   天末怀李白", "ts_102.txt"));
		list.add(new KeyValue("杜甫   奉济驿重送严公四韵", "ts_103.txt"));
		list.add(new KeyValue("杜甫   别房太尉墓", "ts_104.txt"));
		list.add(new KeyValue("杜甫   旅夜书怀", "ts_105.txt"));
		list.add(new KeyValue("杜甫   登岳阳楼", "ts_106.txt"));
		list.add(new KeyValue("王维   辋川闲居赠裴秀才迪", "ts_107.txt"));
		list.add(new KeyValue("王维   山居秋暝", "ts_108.txt"));
		list.add(new KeyValue("王维   归嵩山作", "ts_109.txt"));
		list.add(new KeyValue("王维   终南山", "ts_110.txt"));
		list.add(new KeyValue("王维   酬张少府", "ts_111.txt"));
		list.add(new KeyValue("王维   过香积寺", "ts_112.txt"));
		list.add(new KeyValue("王维   送梓州李使君", "ts_113.txt"));
		list.add(new KeyValue("王维   汉江临泛", "ts_114.txt"));
		list.add(new KeyValue("王维   终南别业", "ts_115.txt"));
		list.add(new KeyValue("孟浩然 临洞庭上张丞相", "ts_116.txt"));
		list.add(new KeyValue("孟浩然 与诸子登岘山", "ts_117.txt"));
		list.add(new KeyValue("孟浩然 宴梅道士山房", "ts_118.txt"));
		list.add(new KeyValue("孟浩然 岁暮归南山", "ts_119.txt"));
		list.add(new KeyValue("孟浩然 过故人庄", "ts_120.txt"));
		list.add(new KeyValue("孟浩然 秦中感秋寄远上人", "ts_121.txt"));
		list.add(new KeyValue("孟浩然 宿桐庐江寄广陵旧游", "ts_122.txt"));
		list.add(new KeyValue("孟浩然 留别王维", "ts_123.txt"));
		list.add(new KeyValue("孟浩然 早寒江上有怀", "ts_124.txt"));
		list.add(new KeyValue("刘长卿 秋日登吴公台上寺远眺", "ts_125.txt"));
		list.add(new KeyValue("刘长卿 送李中丞归汉阳别业", "ts_126.txt"));
		list.add(new KeyValue("刘长卿 饯别王十一南游", "ts_127.txt"));
		list.add(new KeyValue("刘长卿 寻南溪常山道人隐居", "ts_128.txt"));
		list.add(new KeyValue("刘长卿 新年作", "ts_129.txt"));
		list.add(new KeyValue("钱起   送僧归日本", "ts_130.txt"));
		list.add(new KeyValue("钱起   谷口书斋寄杨补阙", "ts_131.txt"));
		list.add(new KeyValue("韦应物 淮上喜会梁川故人", "ts_132.txt"));
		list.add(new KeyValue("韦应物 赋得暮雨送李胄", "ts_133.txt"));
		list.add(new KeyValue("韩翃   酬程延秋夜即事见赠", "ts_134.txt"));
		list.add(new KeyValue("刘脊虚 阙题", "ts_135.txt"));
		list.add(new KeyValue("戴叔伦 江乡故人偶集客舍", "ts_136.txt"));
		list.add(new KeyValue("卢伦   送李端", "ts_137.txt"));
		list.add(new KeyValue("李益   喜见外弟又言别", "ts_138.txt"));
		list.add(new KeyValue("司空曙 云阳馆与韩绅宿别", "ts_139.txt"));
		list.add(new KeyValue("司空曙 喜见外弟卢纶见宿", "ts_140.txt"));
		list.add(new KeyValue("司空曙 贼平后送人北归", "ts_141.txt"));
		list.add(new KeyValue("刘禹锡 蜀先主庙", "ts_142.txt"));
		list.add(new KeyValue("张藉   没蕃故人", "ts_143.txt"));
		list.add(new KeyValue("白居易 草", "ts_144.txt"));
		list.add(new KeyValue("杜牧   旅宿", "ts_145.txt"));
		list.add(new KeyValue("许浑   秋日赴阙题潼关驿楼", "ts_146.txt"));
		list.add(new KeyValue("许浑   早秋", "ts_147.txt"));
		list.add(new KeyValue("李商隐 蝉", "ts_148.txt"));
		list.add(new KeyValue("李商隐 风雨", "ts_149.txt"));
		list.add(new KeyValue("李商隐 落花", "ts_150.txt"));
		list.add(new KeyValue("李商隐 凉思", "ts_151.txt"));
		list.add(new KeyValue("李商隐 北青萝", "ts_152.txt"));
		list.add(new KeyValue("温庭筠 送人东游", "ts_153.txt"));
		list.add(new KeyValue("马戴   灞上秋居", "ts_154.txt"));
		list.add(new KeyValue("马戴   楚江怀古", "ts_155.txt"));
		list.add(new KeyValue("张乔   书边事", "ts_156.txt"));
		list.add(new KeyValue("崔涂   除夜有怀", "ts_157.txt"));
		list.add(new KeyValue("崔涂   孤雁", "ts_158.txt"));
		list.add(new KeyValue("杜荀鹤 春宫怨", "ts_159.txt"));
		list.add(new KeyValue("韦庄   章台夜思", "ts_160.txt"));
		list.add(new KeyValue("僧皎然 寻陆鸿渐不遇", "ts_161.txt"));
		Menu_File_Map.put("五言律诗", list);

		list = new ArrayList<KeyValue>();
		list.add(new KeyValue("陈子昂 登幽州台歌", "ts_040.txt"));
		list.add(new KeyValue("李颀   古意", "ts_041.txt"));
		list.add(new KeyValue("李颀   送陈章甫", "ts_042.txt"));
		list.add(new KeyValue("李颀   琴歌", "ts_043.txt"));
		list.add(new KeyValue("李颀   听董大弹胡笳声兼寄语弄房给事", "ts_044.txt"));
		list.add(new KeyValue("李颀   听安万善吹筚篥歌", "ts_045.txt"));
		list.add(new KeyValue("孟浩然 夜归鹿门山歌", "ts_046.txt"));
		list.add(new KeyValue("李白   庐山谣寄卢侍御虚舟", "ts_047.txt"));
		list.add(new KeyValue("李白   梦游天姥吟留别", "ts_048.txt"));
		list.add(new KeyValue("李白   金陵酒肆留别", "ts_049.txt"));
		list.add(new KeyValue("李白   宣州谢朓楼饯别校书叔云", "ts_050.txt"));
		list.add(new KeyValue("岑参   走马川行奉送封大夫出师西征", "ts_051.txt"));
		list.add(new KeyValue("岑参   轮台歌奉送封大夫出师西征", "ts_052.txt"));
		list.add(new KeyValue("岑参   白雪歌送武判官归京", "ts_053.txt"));
		list.add(new KeyValue("杜甫   韦讽录事宅观曹将军画马图", "ts_054.txt"));
		list.add(new KeyValue("杜甫   丹青引赠曹霸将军", "ts_055.txt"));
		list.add(new KeyValue("杜甫   寄韩谏议", "ts_056.txt"));
		list.add(new KeyValue("杜甫   古柏行", "ts_057.txt"));
		list.add(new KeyValue("杜甫   观公孙大娘弟子舞剑器行·并序", "ts_058.txt"));
		list.add(new KeyValue("元结   石鱼湖上醉歌·并序", "ts_059.txt"));
		list.add(new KeyValue("韩愈   山石", "ts_060.txt"));
		list.add(new KeyValue("韩愈   八月十五夜赠张功曹", "ts_061.txt"));
		list.add(new KeyValue("韩愈   谒衡岳庙遂宿岳寺题门楼", "ts_062.txt"));
		list.add(new KeyValue("韩愈   石鼓歌", "ts_063.txt"));
		list.add(new KeyValue("柳宗元 渔翁夜傍西岩宿，晓汲清湘燃楚竹。 渔翁", "ts_064.txt"));
		list.add(new KeyValue("白居易 长恨歌", "ts_065.txt"));
		list.add(new KeyValue("白居易 琵琶行·并序", "ts_066.txt"));
		list.add(new KeyValue("李商隐 韩碑", "ts_067.txt"));
		list.add(new KeyValue("高适   燕歌行·并序", "ts_068.txt"));
		Menu_File_Map.put("七言古诗", list);

		list = new ArrayList<KeyValue>();
		list.add(new KeyValue("张九龄 感遇·其一", "ts_001.txt"));
		list.add(new KeyValue("张九龄 感遇·其二", "ts_002.txt"));
		list.add(new KeyValue("李白   下终南山过斛斯山人宿置酒", "ts_003.txt"));
		list.add(new KeyValue("李白   月下独酌", "ts_004.txt"));
		list.add(new KeyValue("李白   春思", "ts_005.txt"));
		list.add(new KeyValue("杜甫   望岳", "ts_006.txt"));
		list.add(new KeyValue("杜甫   赠卫八处士", "ts_007.txt"));
		list.add(new KeyValue("杜甫   佳人", "ts_008.txt"));
		list.add(new KeyValue("杜甫   梦李白·其一", "ts_009.txt"));
		list.add(new KeyValue("杜甫   梦李白·其二", "ts_010.txt"));
		list.add(new KeyValue("王维   送綦毋潜落第还乡", "ts_011.txt"));
		list.add(new KeyValue("王维   送别", "ts_012.txt"));
		list.add(new KeyValue("王维   青溪", "ts_013.txt"));
		list.add(new KeyValue("王维   渭川田家", "ts_014.txt"));
		list.add(new KeyValue("王维   西施咏", "ts_015.txt"));
		list.add(new KeyValue("孟浩然 秋登兰山寄张五", "ts_016.txt"));
		list.add(new KeyValue("孟浩然 夏日南亭怀辛大", "ts_017.txt"));
		list.add(new KeyValue("孟浩然 宿业师山房待丁大不至", "ts_018.txt"));
		list.add(new KeyValue("王昌龄 同从弟南斋玩月忆山阴崔少府", "ts_019.txt"));
		list.add(new KeyValue("邱为   寻西山隐者不遇", "ts_020.txt"));
		list.add(new KeyValue("綦毋潜 春泛若耶溪", "ts_021.txt"));
		list.add(new KeyValue("岑参   与高适薛据登慈恩寺浮图", "ts_022.txt"));
		list.add(new KeyValue("元结   贼退示官吏·并序", "ts_023.txt"));
		list.add(new KeyValue("韦应物 郡斋雨中与诸文士燕集", "ts_024.txt"));
		list.add(new KeyValue("韦应物 初发扬子寄元大校书", "ts_025.txt"));
		list.add(new KeyValue("韦应物 寄全椒山中道士", "ts_026.txt"));
		list.add(new KeyValue("韦应物 长安遇冯著", "ts_027.txt"));
		list.add(new KeyValue("韦应物 夕次盱眙县", "ts_028.txt"));
		list.add(new KeyValue("韦应物 东郊", "ts_029.txt"));
		list.add(new KeyValue("韦应物 送杨氏女", "ts_030.txt"));
		list.add(new KeyValue("柳宗元 晨诣超师院读禅经", "ts_031.txt"));
		list.add(new KeyValue("柳宗元 溪居", "ts_032.txt"));
		Menu_File_Map.put("五言古诗", list);

		for (Map.Entry<String, List<KeyValue>> entry : Menu_File_Map.entrySet()) {
			AllList.addAll(entry.getValue());
			SearchList.addAll(entry.getValue());
		}

	}

	static class KeyValue {
		private String value;
		private String key;

		public KeyValue(String value, String key) {
			this.key = key;
			this.value = value;
		}

		public String getValue() {
			return value;
		}

		public void setValue(String value) {
			this.value = value;
		}

		public String getKey() {
			return key;
		}

		public void setKey(String key) {
			this.key = key;
		}

		@Override
		public String toString() {
			return value;
		}
	}
}
